### ISSUE TITLE
[Request] Whitelist mode for sounds

### ISSUE THREAD

**Issue by Shahelion** [OreCruncher/BetterRain#100]
The blacklist is good, but if I only want a few sounds, I have to disable all the ones I don't want. With a whitelist, that takes much less.

**Comment by OreCruncher** [comment]
I understand what you are requesting.  This may seem like a strange request, but can you give me an example of what you are actually wanting to do in terms of what sounds you want enabled/disabled.

EDIT: In case you are wondering people have a tendency to phrase things in terms of a solution and not really stating the underlying problem they are grappling with.  My goal is to better understand what you are thinking and wanting.  There may be better alternatives to solving the problem than "white list vs. black list".

**Comment by Shahelion** [comment]
Basically if I want to have a couple of the sounds from each category enabled. So I can't disable the entire category, so I have to disable each one I don't want one-by-one. An example being I wanted to disable most biome sounds (too many mob sounds already in my pack) but I wanted to leave the owl and wolf ones. Being able to simply whitelist those three would be easier than blacklisting every other biome sound.

**Comment by OreCruncher** [comment]
OK - so the use case is that you are trying to balance the sounds throughout the entire pack rather than something like "I am terrified of monster sounds".

**Comment by OreCruncher** [comment]
Just thought of a wrinkle.  The blocked sounds work on _all_ sounds that can be produced by Minecraft/mods.  This means if you take the whitelist approach you would have to whitelist Minecraft as well as other mod sounds if you want to hear them.

**Comment by Shahelion** [comment]
Oh ok. I thought the sounds from this mod were all separate.

**Comment by OreCruncher** [comment]
Well, the sounds in this mod are separate in terms of the mod ID.  However, the cull and blocked sound lists will apply to _all_ sounds, vanilla and modded.  Primarily those are intended to manage Dynamic Surroundings and vanilla, but other modded sounds could be added to these lists.

**Comment by OreCruncher** [comment]
I can't see a good way to balance by doing a whitelist config setting.  I am adding config options where a player can enable/disable blocking of sounds within the Configuration GUI which would go a long way towards making sound blocking more manageable. Going to close this one out because of [#107].
