### ISSUE TITLE
[Suggestion/Idea] In your face!

### ISSUE THREAD

**Issue by Drakoflame** [OreCruncher/BetterRain#105]
So, while commenting on something over on the curseforge page, Cruncher replied to me with a new thing that'll let players pick and choose what sounds are going to play via an ugly list. He said "Not too hard once I figured out a way to do some kung fu on it. :)" and I thought of Enviromine, which adds a bunch of things to the player, and then I realized "DS is all about aesthetic things..."

Anyway, I don't know how to tie that into what my idea was. I was thinking of some sort of effect that would kinda go over the players view. It would be disabled by default (as I can imagine it would get VERY annoying to some players), but it would add a few effects. In the desert, not durring a storm, the player would get hot, and start sweating, so maybe sweat drops forming around the player/on the players face and run down the edge of the screen. During a storm however, well there's sand in your face, kinda makes it hard to see, so maybe some sort of blur filter/occasional sand particles in the players view obstructing things. When diving under water (in ocean biomes) salt water hurts your eyes, so things would be fuzzy, but wearing a helmet of any kind will prevent said blur (ontop of the already dim view underwater). when surfacing there would be a bit of a glare afterwords as the water drained. And maybe slightly wet vision/water drops running down a players view while in the rain!. Maybe durring blizards/wind storms, the player would get snow flakes in their face or something. I can't think of anything else, but if anyone can think of some kind of effect that would be cool to see (Irony XD).

I hope this is an idea others would like, I myself would love to see things like this, it would be especially interesting for wasteland type survival, where storms whip sand in your face and make it hard to see,

**Comment by OreCruncher** [comment]
These types of things could be interesting.  They may not belong in Dynamic Surroundings.  Reason I say that is that the player can turn a lot of the stuff off in Dynamic Surroundings by altering the config and not affect the game play of any others on a server.

Something like you propose would be good in some sort of "difficulty" pack where weather and circumstances have more of an effect on the player and game play and will affect all players equally, and those options couldn't be turned off.

(I have had similar thoughts and have not put them into Dynamic Surroundings for the above mentioned reason.  I haven't forgotten about them...)

**Comment by Drakoflame** [comment]
Well that was why I said it would be disabled by default, and yes, it would be something good for a "hardcore" pack, but I havn't the foggiest on how to code XD.

**Comment by Sunconure11** [comment]
I think Psychedelicraft might be doing similar things, through the usage of shaders and such. For instance, it has an effect for when you just get out of water, effects for very hot biomes (heat haze), as well as a lens flare for the sun.

Note: If you go this route, I suggest adding an option to turn off the shaders for such effects, shaders can be really harsh on lower end PCs.

**Comment by Drakoflame** [comment]
@Sunconure11 I know exactly what your saying, and my intention with the idea is that they would default start as off, as either some players wouldn't like the (or some of the) effects, and that some computers might not be able to handle it, or be able to handle DS to begin with, as it is kinda intensive with the sound checks. But either way, I don't think Cruncher intends on adding it simply because a lot of players might not like it, and it would more be a feature for a "hardcore" map. Speaking of... I need to go and get the "Wastelands" mod again and see how horribly broken it is, especially after not being update (YET AGAIN) for a year or so... why do all the good terrain gen mods die? Its funny because the last owner is still active and modding I think, even was helping with the current modder, but the current one has just... dissapeared and has stopped development unfortunately... it had a lot of potential too!

**Comment by O13SC3N3** [comment]
RTG is alive, Climate Control is Alive, and UBC is alive. Zeno is a BAMF and works almost night and day like Cruncher here. The heatwaves , water blur, and flares would fit in to Dynamic. But like sunconure11 said shaders need to be opt out. And tbh the easiest way to use that mod on lowwer end pcs is to not use botania or turn botania shaders off. The 2 mods hate each other with a passion.

If Psychedelicraft craft just had the module for the environments id still use it. The drugs got out of hand, though fun for awhile. The main lsd trips would crash users around ic2 machines and such. Granted not really the mods fault, its just the way ic2 is rendered. Optifine does the same thing with certain mods.

**Comment by Drakoflame** [comment]
Hey @OreCruncher any updates on this one? I know you added noisy armor (awesome too btw :D is there config options to add your own armor? Or maybe a way to detect what "type" of armor something is? but that's a different subject). If this feature is/was added, like I said before, it should be off by default because some texturepacks are incomatible, and some people might find it to annoying that every time they put on a helmet they feel like their wearing a pumpkin.

**Comment by OreCruncher** [comment]
There is a way to add modded armor to the internal lists so the sounds play.  The [EnderIO config Json](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/resources/assets/dsurround/data/enderio.json#L6) has an example of what it would look like.  I wish there was a way to detect but there isn't a standard way of doing that.

I have been thinking of visual effects on the screen.  Some mods do similar things (like blood splatters).  I did look into heat haze as @O13SC3N3 mentioned above but that can get real complicated and would require shaders to do it justice.  The restricted view based on helmet worn is interesting, but that strays into altering the game mechanics.  The next major release cycle I can see about putting in a prototype "helmet hud" to test the waters.

**Comment by Sunconure11** [comment]
Fossils and Archaeology managed to pull off a restricted view with it's helmet, also Apocalypse by Father_Toast did it with its bucket helmet, and of course, vanilla pumpkins do it.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
