### ISSUE TITLE
Disable Aurora in TheEnd

### ISSUE THREAD

**Issue by LemADEC** [OreCruncher/BetterRain#106]
As of DynamicSurroundings-1.7.10-1.0.5.2BETA, there's Aurora in the End dimension.
This seems out of place, would like to have a configuration to limit auroras to specific dimension or biome.

**Comment by OreCruncher** [comment]
Thanks for reminding me.  I was planning on disabling.  The star field obscures it so it really isn't worth it.

**Comment by OreCruncher** [comment]
Change made for BETA pushed to CurseForge.
