### ISSUE TITLE
Weird crash involving death

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#109]
http://pastebin.com/QuPpPh8t

I am the modpack dev of the server this happened on, but, this might be an issue. Apparently when this user dies, players near him crash.

Also, might I make a minor suggestion? Add a configuration file for players to define footstep sounds via the oredictionary on their end, so they do not have to rely on built in settings to set up any sounds in case they are using either a custom or undiscovered definition.

**Comment by OreCruncher** [comment]
Gotta love malformed events.

Providing user driven sound configuration is evolving.  Some of the sounds aren't simple and straight forward.  Some blocks require a composite of sounds, or several different sound configurations depending on what the player is doing.

**Comment by OreCruncher** [comment]
BETA pushed to CurseForge containing fix.
