### ISSUE TITLE
Aesthetic: Desert sandstorm at night makes it feel like daytime

### ISSUE THREAD

**Issue by PitchBright** [OreCruncher/BetterRain#11]
I'm just being fussy but I feel like when there's a desert sandstorm at night, the colourization of the area makes it feel like it has become day. See attached image for comparison of night with and without sandstorm: https://imgur.com/a/2u9Ph

**Comment by OreCruncher** [comment]
I noticed the same thing. :)  It's on my list of things to deal with.  Essentially I need to "darken" the fog color based on light levels.

**Comment by PitchBright** [comment]
Cool cool.

**Comment by OreCruncher** [comment]
Posted mod updates to CurseForge that contain this feature: http://minecraft.curseforge.com/projects/better-rain/files. Applies to 1.7.10-1.0.2.1BETA and 1.8.9-1.1.0.3ALPHA

**Comment by PitchBright** [comment]
Awesome, thanks!
