### ISSUE TITLE
Visual Issue

### ISSUE THREAD

**Issue by mathematiqueNageur** [OreCruncher/BetterRain#112]
I recently updated this mod and I encountered an interesting issue. My best way to describe it is like a blindness potion with a white color upon initial world creation and respawn. the only solution I could find was to restart my client. 
Mods in Use: [Mischief Managed-1.0.zip](https://github.com/OreCruncher/BetterRain/files/159683/Mischief.Managed-1.0.zip)
Visual of the Issue:
![2016-03-04_22 38 25](https://cloud.githubusercontent.com/assets/9004152/13545698/efe83042-e259-11e5-98e7-29ab84c78bdb.png)
![2016-03-04_22 38 28](https://cloud.githubusercontent.com/assets/9004152/13545700/f3d4bcc0-e259-11e5-8693-525ad5002d6a.png)
![2016-03-04_22 38 30](https://cloud.githubusercontent.com/assets/9004152/13545702/f6aac14c-e259-11e5-863b-ab6c373832ed.png)
![2016-03-04_22 38 33](https://cloud.githubusercontent.com/assets/9004152/13545703/f898c1d4-e259-11e5-8e2d-94c5976241a6.png)
![2016-03-04_22 38 35](https://cloud.githubusercontent.com/assets/9004152/13545704/fa80c7da-e259-11e5-9f63-c0f9b82e854e.png)

**Comment by OreCruncher** [comment]
Which version of the mod are you using?

**Comment by mathematiqueNageur** [comment]
1.8.9-2.0.4.10

**Comment by OreCruncher** [comment]
Thought it was 1.8.9.  Try the latest 1.8.9-2.0.5.4BETA.

**Comment by mathematiqueNageur** [comment]
That appears to have fixed it. Thank you!
