### ISSUE TITLE
1.8 Support

### ISSUE THREAD

**Issue by djtdwpslays** [OreCruncher/BetterRain#114]
I see links for Minecraft versions 1.7.10 and 1.8.9, but are there any builds just for 1.8?

**Comment by OreCruncher** [comment]
No builds for 1.8.  Currently no plans to provide one - it's a pain keeping 1.7.10 and 1.8.9 updated. :\

**Comment by djtdwpslays** [comment]
I understand that and don't blame you for it!

Thanks!
