### ISSUE TITLE
Crash mentioning Dynamic Surroundings with More Enchantments mod

### ISSUE THREAD

**Issue by plazia** [OreCruncher/BetterRain#118]
Awesome mod BTW - Really love it.

Installed a mod called More Enchantments mod. Enchanted a vanilla bow with Quickdraw max level, Pulled the bow back about to fire and Boom Crash. I suspect it may be Dynamic Surroundings as that's the first mod mentioned in the crash report but I'm no coder.

Crash report http://pastebin.com/c6USp0Cj

**Comment by OreCruncher** [comment]
Glad you like the mod.

Looks to be another malformed event from a mod.  Getting an item use event with no item in the event payload.  Joy.  To work around this issue disable the bow sound in the Dynamic Surroundings config file.  I will see about making a fix for the release version.

**Comment by OreCruncher** [comment]
Update with fix posted to CurseForge.
