### ISSUE TITLE
[1.8.9-1.1.0.2ALPHA] Incompatibility with Thaumcraft's shaders.

### ISSUE THREAD

**Issue by MrGraphic** [OreCruncher/BetterRain#12]
I noticed some small issues when TC's shaders kick in.
The first one happens when TC changes fog whan player is close to Eldritch Guadian
![de_fog](https://cloud.githubusercontent.com/assets/4780141/12310706/a4019ee4-ba49-11e5-9718-c9b75c3c4014.jpg)
and second when player's vision changes under Unnatural Hunger potion effect:
![hunger](https://cloud.githubusercontent.com/assets/4780141/12310800/33aea1ae-ba4a-11e5-8fc0-5cb372d4deb8.jpg)

**Comment by OreCruncher** [comment]
I think what is happening here is that BetterRain and Thaumcraft is fighting over the fog in Minecraft.  Left hand doesn't know what the right hand is doing.  Both of the things you mention are all part of Minecraft's fog rendering.  I need to check into whether I can detect these conditions and not take over.  My preference is to let other mods do their custom fog processing without stepping on them.

**Comment by MrGraphic** [comment]
My exact thought. Btw thank you for taking over this small but fantastic mod not to mention your expansion. Thanks :).

**Comment by OreCruncher** [comment]
Azanor/thaumcraft-5#233

**Comment by OreCruncher** [comment]
A follow up.  I made changes to fog rendering since this issue came up, and I was wondering if you had a chance to see whether those changes made a positive impact on Thaum fog behavior.

**Comment by OreCruncher** [comment]
I am backporting fog effects from 1.10.x+ branches and it should address this issue.

**Comment by OreCruncher** [comment]
Fixes for compat should be in v1.0.6.1 along with other fog tweaks.
