### ISSUE TITLE
[CRASH] NPE at seemingly random intervals (1.7.10)

### ISSUE THREAD

**Issue by novasolarius** [OreCruncher/BetterRain#120]
Here's the latest crashlog: http://pastebin.com/shsy91yH
I have about half a dozen of these now, and yet I can't figure out why the NPE happens. I'm sorry that I can't provide more information.

Also, thank you for making DS, one of my very favourite mods (when it doesn't jumpscare me with loud noises). Keep up the amazing work.

**Comment by OreCruncher** [comment]
Yeah - been dogging this one for a bit.  Looks to be a Minecraft bug.  The next release version will have a work around to prevent Minecraft from crashing.

**Comment by novasolarius** [comment]
Thank you very much.

**Comment by OreCruncher** [comment]
Update with fix posted to CurseForge.
