### ISSUE TITLE
cannot be cast EssentialCraftv4

### ISSUE THREAD

**Issue by SvEgiiVEteR** [OreCruncher/BetterRain#125]
1.7.10
https://gist.github.com/7325d10ca8d0ce92069ee4432696958f
how can it solve the problem by configs?
or do I need to wait for an update?

**Comment by OreCruncher** [comment]
Turn off fancy cloud rendering in the dsurround.cfg file.

**Comment by OreCruncher** [comment]
@SvEgiiVEteR Did turning off the fancy cloud handling work?

**Comment by SvEgiiVEteR** [comment]
Yes I was off but not sure what the cause is in them.
but not included.. works well

**Comment by OreCruncher** [comment]
OK.  Going to close.  If you come across anything else let me know.
