### ISSUE TITLE
Bug(with other mods) also solved

### ISSUE THREAD

**Issue by TECHNICOR** [OreCruncher/BetterRain#128]
Hello i play ftb unstable and i have come across a bug; so if it "rains" in the nether and you die the overworld becomes completely dark only with some contours. i was able to go back in the nether and turn off the "rain" after that  i returned to the overworld and could see again. I hope that this was helpful in some way.

**Comment by OreCruncher** [comment]
Which version of the mod are you using?

**Comment by TECHNICOR** [comment]
1.8.9 -2.0.4.10

**Comment by OreCruncher** [comment]
OK.  I fixed some of the fog rendering and those fixes should be in 1.8.9.-2.0.5.6 (the latest).  Prior to the fix the fog colors would look like a film negative under certain conditions.

**Comment by TECHNICOR** [comment]
well that is great, thanks for the responses

**Comment by Sunconure11** [comment]
Shouldn't you close this, @TECHNICOR, if it has been solved?
