### ISSUE TITLE
Galacticraft dimensions

### ISSUE THREAD

**Issue by BernardoCBranco** [OreCruncher/BetterRain#129]
Galacticraft dimensions start having problems with dynamic surroundings installed, the gravity on stations and planets returns to normal, clouds start appearing, the overworld doesn't show beneath the station, the player stops leaving footprints and the HUD disappears.

Without DS:
![2016-04-15_15 56 41](https://cloud.githubusercontent.com/assets/7836631/14565361/b9b084e0-0322-11e6-8514-e8a41b7481b0.png)
![galacticcraftnods](https://cloud.githubusercontent.com/assets/7836631/14565251/15a36692-0322-11e6-948c-1345dab7f6e7.PNG)
![2016-04-15_15 43 16](https://cloud.githubusercontent.com/assets/7836631/14565008/efefa2f4-0320-11e6-8ce9-6540d947d3e8.png)

With DS:
![2016-04-15_15 15 04](https://cloud.githubusercontent.com/assets/7836631/14564102/eb699838-031c-11e6-8fa7-425812008683.png)
![2016-04-15_15 15 13](https://cloud.githubusercontent.com/assets/7836631/14564113/f3310010-031c-11e6-9647-ad0fa5d5e800.png)
![2016-04-15_15 43 58](https://cloud.githubusercontent.com/assets/7836631/14565016/f941e1dc-0320-11e6-9a1f-5f06da135f8a.png)

**Comment by OreCruncher** [comment]
Which version of DS are you using?

**Comment by BernardoCBranco** [comment]
1.0.5.6

**Comment by OreCruncher** [comment]
Turn off Fancy Cloud handling in the dsurround.cfg file.  BTW, which version of Galacticraft is this?

**Comment by BernardoCBranco** [comment]
It seems that disabling Fancy Cloud handling fixed it. Ty :)

**Comment by OreCruncher** [comment]
Cool.  Galacticraft version?  I need to test some things out and get some other dimension data so I can update some code.  DS needs to "black list" these dimensions from fancy cloud handling by default.

**Comment by BernardoCBranco** [comment]
Ok. It's galacticraft version 3.0.12.454.

**Comment by OreCruncher** [comment]
Thanks!

**Comment by BernardoCBranco** [comment]
No problem, thanks for the help. :)

**Comment by OreCruncher** [comment]
Because of the various compatibility issues I have been encountered I am going to remove the fancy cloud handling.  Thought it was nice to have I don't think the value warrants the "bad behavior" that was incurred to make it work.
