### ISSUE TITLE
Calendar API support

### ISSUE THREAD

**Issue by PitchBright** [OreCruncher/BetterRain#13]
A few other modders and myself, discussed my observation of the need for a calendar API for mods that do things based on time, season, and day/night cycles, sleeping, sky-stuff... etc… and CallMeFoxie from the BetterSleeping mod worked her java wizardry and made it happen.

If you have plans for Auroras, and other sky-based/time-based events such as Rainbows (Falling Stars, Meteor Showers, and other atmospheric phenomena - that I'm probably gonna ping ya for :D)… it'd be great it you added support for the API.

Other mods such as Stellar Sky, The Seasons Mod, BetterSleeping2, and Just Another Spawner will be adding it shortly.

https://github.com/CallMeFoxie/Calendar
http://jenkins.foxiehost.eu/job/Calendar%20-%201.7.10/1/

**Comment by OreCruncher** [comment]
This is interesting.  I will take a look at it to see how I can take advantage.

**Comment by mindcloud69** [comment]
I would love to see this support. The potential here for multi-mod integration to create a more dynamic living world would be fantastic.

**Comment by OreCruncher** [comment]
It would.  At the moment though the main thing with integration is Stellar Sky, and for that I make use of the celestial angle and moon brightness for my aurora work.  Doesn't require calendar for that.  HOWEVER, there is are potential integration points for sound like only having a certain sound play during a specific season.  There may be something I could do with leaf color, but at the moment its not on my list of things - primarily because I don't fully understand the foliage color system.

**Comment by PitchBright** [comment]
This mod does the foliage colour system, on a per-season basis. It's going to be getting CalendarAPI support in the near future too actually. He's one of the dudes I work with pretty regularly, and was involved in the CalendarAPI conception. I talk him daily, actually. I can put you guys in touch OreCruncher, if you want to connect on any matters. You'd probably have a lot to talk about actually.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285986-the-seasons-mod-minecraft-1-7-10-build-pre-3

He's also the sorcerer behind the custom rain stuff I had in 1.4.7… that I wanted to flip over to you for implementation here instead. I think we discussed it in #16

**Comment by OreCruncher** [comment]
If a mod is going to do foliage color then I will skip.  My goal for this mod is to put things that no one else has done or a mod had it but isn't being maintained.  Of course, having the ability to configure sound based on season would be good.  For example, In a Forest birds always chirp.  However, in Winter you figure they would change.  Spring would should also have an increase in sound because of all the activity.

I am definately interested in the thunder side of things.  If he has the old source to the 1.4.7 mod I would be interested in seeing what he did.

**Comment by PitchBright** [comment]
Oh ya… good thinkin'… that'd be sweet! I definitely plan on controlling animals-per-season via https://github.com/ProjectZulu/JustAnotherSpawner/issues/153 , so your idea would marry up with that beautifully.

I'll check back with Pony about the source he used in 1.4.7 and see if I can get it off him. He's always busy, and he I get distracted with other TSM related things when we're talking… so I keep forgetting to score that code from him. Whatever he did back in 1.4.7… worked beautifully though. It gave me hella-control over the "when" of rain/thunder.

**Comment by OreCruncher** [comment]
Oh, a suggestion for the animal/season thing.  Should make the breeding cycle long/shorter depending on the season.  Should also apply to villagers, but we don't want to look into too many bedrooms. :)

**Comment by PitchBright** [comment]
OHHhhh… awesome idea! I know just who to get in touch with about that too. Good one, OreCruncher!

**Comment by OreCruncher** [comment]
If CalendarAPI is installed the current season for the dimension will be added to the list of condition tokens for filtering.  If it is not installed "noseason" will be the token.

**Comment by OreCruncher** [comment]
Posted BETAs to CurseForge that use the CalendarAPI to obtain season information http://minecraft.curseforge.com/projects/dynamic-surroundings/files

**Comment by PitchBright** [comment]
_touchdown dance_

I'm looking forward to testing this out with another mod using CAPI, to see if they work as expected!

**Comment by OreCruncher** [comment]
Right now there are no sounds/visuals tied to the season data.  You can see the condition string if you were to turn on debug logging in the config file (it renders some text on the left of the screen regarding Dynamic Surroundings state.)

I need to find different sounds for the biomes.  For example, the forest sound could be split into two separate sounds - a general background "wind in trees" type sound, and another a "wild life" sound track that would be tied to the season.  The mod would play these two tracks at once to make a composite.

EDIT:  There is another further change I plan on making.  Support was recently added for "is it sunrise", etc.  I plan on adding those condition tokens as well, not to mention changing the aurora triggers to better match daylight timings.
