### ISSUE TITLE
crash on log in on server with footstep

### ISSUE THREAD

**Issue by SDUBZ** [OreCruncher/BetterRain#130]
heres the crashreport to help using forge 1.8.9 1855
http://pastebin.com/zvjpF8Y0

**Comment by OreCruncher** [comment]
Does it happen all the time or just sporadically?

**Comment by SDUBZ** [comment]
it just happend today and now it doesnt even let me in ive tried 4 times already and it crashes me back to desktop/loader

**Comment by OreCruncher** [comment]
Connecting to a remote server?

**Comment by SDUBZ** [comment]
to a actual server yes

**Comment by OreCruncher** [comment]
Going to take a look at it with the new updates.  I am doing some refactor work in that area.
