### ISSUE TITLE
Flashing fog

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#131]
I've noticed that in some biomes (dead swamp from BoP), the fog will flash every two seconds. This might be really bad for users with epilepsy, and in general, probably hurt the eyes of normal users.

**Comment by OreCruncher** [comment]
Which version of DS?

**Comment by Sunconure11** [comment]
Latest build on curse (for 1.7.10): DynamicSurroundings-1.7.10-1.0.5.6.jar

**Comment by O13SC3N3** [comment]
Must be gpu related? Not experiencing it.

**Comment by Sunconure11** [comment]
Could it be related to Stellar Sky by any chance? It does change the rendering of the sky.

Alternatively, what about Hardcore Darkness?

**Comment by OreCruncher** [comment]
This will be fixed v1.0.6.1 :)

**Comment by OreCruncher** [comment]
Forgot this issue dangling out here.  Changes for fog went into v1.0.6.1
