### ISSUE TITLE
[Request] Constant "weather" effects, new sounds

### ISSUE THREAD

**Issue by Drakoflame** [OreCruncher/BetterRain#132]
So, a little while back I posted another suggestion/idea about having things like storms causing water effect in rain, frost in snow, and dust in sand storms, I'd also said how I'd need to download the wastelands mod to see how they interact... Well... I've only one complaint, but otherwise holy crap is it perfect?!

So, first of all, due to the forge biome dictionary, the wasteland biomes are pretty much good when it comes to sounds, I've only tested in 3 different ones (as they are the only ones I've been to in my survival worlds) and in the normal "Wasteland" biome, there is wind, constant wind, as well as the "Wasteland Mountain" biome. There are 3 other biomes, the "Ruined City", the "Wasteland Forest", and the "Radio Active Wasteland", which is full of pools of radioactive water that give you poison 2 and arn't fun . _. Anyway! The complaint/issue, the Wasteland Forest biome is a "Forest" biome, so I hear happy birds and forest sounds... in the desolate area... noooooot exactly what is supposed to be there... I know I can fix it in the configs (I think), I"ve just been to lazy to fix it for now, but I was wondering if there could be special sounds, or a way for me to add sounds? For example, in the Wasteland Forest, I think it would be perfect if there was wind, the occasional wood creaking, or twig snapping, even soft howling as the wind cuts through the bare branches. In the city, it would be similar, more muffled (by the buildings) the sound of glass clinking as broken windows drop shards that brake, the occasional skittering of something that survived, a door slamming from the wind (was it... was it?), and then for the mountains, maybe the distant howling of... something... something made by the wasteland... something you never want to meet...

Also, while I was playing, I got the very, very rare rain storm, and was confronted by blinding sand, I couldn't see more than 10 blocks infront of me... almost got killed by zombies a few times... But anyway, What I also would like to request, is maybe a feature that allows you to enable a constant effect in some biomes? For example, wasteland biomes constantly have sand blowing, maybe not as thick as in a storm. Not exactly like in the storms where your vision drops off quickly after a certain distance, but like a constant thing that makes it hazy. It would be the thickest in the normal wasteland, actually cutting your vision at 40 blocks, where as the Forest would be protected by the trees, and be 50-60, the City biome would be 100 or so blocks (very faint, as the buildings mostly block it out), and the Hills one would be around 60-70 blocks. I think it would be fun and a bit more immersive if there was a constant effect in those biomes, as currently to enable the blinding storm, I have to turn rain on, but that means my water collector is constantly getting water... making things a bit to easy...

**Comment by OreCruncher** [comment]
In my mod travels I haven't come across a biome named "Wasteland Forest", so I bet that the matching rule I have in the config will match.  I would have to update the rules to exclude that particular type of Forest when matching.  I could also add wind sound to that biome - pretty straight forward.

As for constant weather effects - that would be a challenge.   Fog is easy since I have biome fog.  Rain like effects, however, are dimension wide.  The blowing sand effect is tied to the global rain.  I like the idea, though.  I will have to see how complicated it would be to do this.  This would also allow biomes with constant rain though it would be strictly aesthetic and not affect the Minecraft view of rain.

**Comment by Drakoflame** [comment]
That'd be awesome Cruncher :D (sadly I've moved on from 1.7.10, which the mod that I was using that inspired this is stuck in p np). But having some sort of constant weather effect would be cool, like a constant drizzle type rain in jungle biomes, or light snowfall up high in Extreme Hills or ice plain/spike biomes as well!

I think there's a lot of cool fun stuff that can be done in 1.10 as well, I'd love to see what you do with the new magma block! Gunna go make a new suggestion for them > u>

**Comment by OreCruncher** [comment]
@Drakoflame For the next updates (1.7.10/1.10.2/1.11.x) I will be tweaking the biome rules to make sure there are no forest sounds in the Wasteland Forest.  (There isn't a 1.11.x Wasteland Mod version that I can see - updating just in case one pops out.)

**Comment by Drakoflame** [comment]
Awesome @OreCruncher looking forward to the update. A bit sad there isn't a 1.11.2 version of the mod _yet_, but eagerly awaiting one :D

**Comment by OreCruncher** [comment]
Hopefully it will be an easy port to 1.12 when it comes.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
