### ISSUE TITLE
[Enhancement] Potion HUD position

### ISSUE THREAD

**Issue by LakMoore** [OreCruncher/BetterRain#134]
This mod has the nicest looking Potions HUD that I have found but it is top-left aligned only.  It would be WONDERFUL if alignment could be changed in the config. 

Top aligned would pile the notifications downwards.
Bottom aligned would pile them upwards.

Left/right aligned shouldn't change the piling style... in my opinion.

**Comment by OreCruncher** [comment]
Right now as you noticed the HUD alignment is offset based using the upper left corner of the display.  I will tag this as an enhancement for the 1.10.2 repository to allow you to specify the corner of the display, and apply the offsets relative to the corners.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
