### ISSUE TITLE
Sounds like iron when walking with 1 leg on block other on air

### ISSUE THREAD

**Issue by Timtrinox** [OreCruncher/BetterRain#135]
When walking between a solid block and air its possible to hear the metal walking sound.

**Comment by Sunconure11** [comment]
Try this fork, since OreCruncher has vanished off the face of the Earth, if you want any issues fixed at this point.

https://github.com/Abastro/BetterRain

**Comment by OreCruncher** [comment]
Actually I am on vacation. Don't tell anyone. 😀

**Comment by OreCruncher** [comment]
@BeefyTim have you tried the fork?  Also what version of the mod were you using?  I noticed the problem with 1.7.10 and Crackpack, but I don't hear it with my 1.10.2 build I am working on.

**Comment by OreCruncher** [comment]
@BeefyTim @Sunconure11 I found the problem.  The call I am using to the Forge registries is returning AIR for a bad block.  This causes the existing AIR information to be overwritten with the metal sound.  Joy.  Going to be rolling out an update for this and a small number of fixes.

**Comment by OreCruncher** [comment]
Pushed 1.0.5.7 for Minecraft 1.7.10 to CurseForge.  No plans for 1.8.9.
