### ISSUE TITLE
Presence Footsteps WAY quieter than the official mod

### ISSUE THREAD

**Issue by Timtrinox** [OreCruncher/BetterRain#136]
When walking, the footsteps sounds are ~50% quieter than that of the original liteloader mod.
This has been tested, and its almost inaudible compared to the liteloader ver.

**Comment by Drakoflame** [comment]
If you want to turn them up, you need to go into the settings and adjust it. I'm not sure where it is exactly, but its default is set to 0.05, I have mine set to 0.2, and that makes it loud enough to hear it but not deffening when you walk through glass or over something else XD

**Comment by OreCruncher** [comment]
Yes.  I turned down the volume from the actual version.  Main reason is that I personally use headphones and it was quite loud. :)  As @Drakoflame  mentions you can adjust the setting higher.  I am open to changing the default if there is some sort of consensus.

**Comment by OreCruncher** [comment]
Pushed 1.7.10 version of DS that changes the default sound scale to 0.15 to match the 1.10.2/1.11.2 versions.
