### ISSUE TITLE
[Request] Magma blocks!

### ISSUE THREAD

**Issue by Drakoflame** [OreCruncher/BetterRain#137]
Now that Cruncher has returned from the land of "Real Life" and (potentially) has more time to work on this mod once again, I would like to request/recommend that the new 1.10 "Magma Block" emit some sort of fancy particle :D

It would be cool if they would have random fits of lava pops like lava sometimes does, where it shoots out a large cluster of the weir fire pop things and spits black smoke. It would also be cool if they would shoot off something that looked like a burning ember, as this block is absolutely perfect for fireplaces with smoldering coals!

Glad to see you back safe and sound Cruncher, I wish you good travels in the future, and health to you and those around you!!

**Comment by OreCruncher** [comment]
I have been thinking about what to do with the magma block.  I could do something along the lines of mycelium (those small particles that emit from the surface).  Have thought about having little bitty black smoke particles as well.  Whatever I do I don't think I want spot sounds coming from them.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
