### ISSUE TITLE
Default settings for sun glow at the rain

### ISSUE THREAD

**Issue by vrnRaptor** [OreCruncher/BetterRain#139]
When there is rain at any rate, I have always seen the sun in the sky. Please add a setting to the configuration by default to be able to change the value of the brightness of the sun in the rain.

**Comment by OreCruncher** [comment]
@vrnRaptor  It's the density of fog and its color that gives you the impression of brightness.  The more intense rain results in thicker darker fog.  If the rain is light it is possible to see the sun and have a brighter sky as if it were a sun shower.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
