### ISSUE TITLE
[1.11] Some particles not working

### ISSUE THREAD

**Issue by ghost** [OreCruncher/BetterRain#143]
@OreCruncher I tried making a cool blinking command block creation for some mobs, but endRod or totem particles do this: they blink with a 1x1 pixel dot then disappear in a split second. PLEASE FIX! This issue was posted in the unofficial version of Dynamic Surroundings too.

**Comment by OreCruncher** [comment]
@Rapolis what version of the mod are you using?

**Comment by OreCruncher** [comment]
NVM.  The particle sheet needed to be updated.  You can track the issue in the new repository [here](https://github.com/OreCruncher/DynamicSurroundings/issues/5).
