### ISSUE TITLE
Unexpected Error on 1.7.10

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#144]
http://pastebin.com/JvPKsPWF

**Comment by OreCruncher** [comment]
This happen sporadically or all the time?  Also, here is a scenario:

- Start client and load up world things are fine
- Quit a world and reload the same/another without exiting the client

**Comment by Sunconure11** [comment]
It happened when I tried to test to see if specific OreDictionaries from a pull I created got put in, by placing it on a block (oreGeneric). The result was me crashing when I stepped on the block. It kept happening until I removed the definition.

**Comment by OreCruncher** [comment]
Did you build the mod from scratch, or do a reload?

**Comment by Sunconure11** [comment]
I used minetweaker to place the definition on the block.

**Comment by OreCruncher** [comment]
What I am trying to understand is the sequence of events to get to the point of the crash.  The scenario I posted above is a way to do that, but it appears you are doing something different.  It could be the same problem but triggered a different way.  I just don't know if that is the case though.

**Comment by OreCruncher** [comment]
@Sunconure11 Try this jar out: https://github.com/OreCruncher/BetterRain/releases/tag/1.0.5.8  It has the fix for the scenario I outlined above.

**Comment by Sunconure11** [comment]
Alright, I'll try it in a bit.

**Comment by Sunconure11** [comment]
Error appears to have stopped.

**Comment by OreCruncher** [comment]
Pushed a 1.0.5.8 BETA that has the fix.
