### ISSUE TITLE
[Request] Flap flap flap flap

### ISSUE THREAD

**Issue by Drakoflame** [OreCruncher/BetterRain#145]
I like elytras, you like elytras, WE ALL LOVE ELYTRAS! But the only time we hear them, is when your flying really fast and have wind rushing past your ears... you'd think that if your spamming the shift key, you'd hear them opening... right? I mean you see them open when you shift (in F5 mode), so why not _HEAR_ them to?! I know this might not be something doable due to 1.7.10 an 1.8 not having elytras, but maybe there could be a way to make it "work"? just auto-disable the feature in those versions? or wait until they're not supported anymore... either way... it would be cool if Elytra's had some more sounds to them aside from rushing wind when your rocketing towards the ground (literally)

**Comment by Sunconure11** [comment]
It might be better to take this to the other repo. There are mods that backport them though.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
