### ISSUE TITLE
Request: Even Beterer Rain

### ISSUE THREAD

**Issue by Drakoflame** [OreCruncher/BetterRain#16]
Okay, because Curseforge ate my comment p nq and I had spent so much time putting that one in, and I liked it so much... ANYWAY, is it possible to make a config option so that sleeping doesn't reset the rain cycle? Because, personally, with BR installed, I enjoy the rain... the sounds that it makes... the faint mist around me when I'm working in my garden, the sound of the pitterpatter on the roof of my green house, the muffled roar as I cook something from Harvest Craft inside my house, the lovely faint pounding as brew some ale in the basement, courtesy of Growth Craft (Community Edition). All the sounds are enhanced by the Sound Filters mod. I highly recommend it... after you play with it a little while, you'll get used to the faint echoes, reverbs, and other small enhancements, such as muffled sounds behind walls, distorted and muffled things while underwater.... it just... I recommend it as well p uq

Anyway, unless Github eats comments as well, you SHOULD get this one XD

**Comment by OreCruncher** [comment]
I use GrowthCraft and Sound Filters, too.  IMO they are very much underrated by the modded Minecraft community. Sound Filters make it feel like you are in a cave with that slight reverb it produces - very nice.

As for the sleep function I will have to check and see.  It's not impossible - just have to see how convoluted such an effort would be.  If I did this the default would be the current behavior, and the modpack author/server owner would have to make a setting change to put it into effect.

**Comment by Drakoflame** [comment]
Thats what I was asking for. I know some people don't like rain, and they use sleeping to get rid of it, but I actually like the rain that Better Rain adds, and I want it to be there when I wake up, sure, I might have nasty mobs trying to eat me when I wake up, but that doesn't bother me if I get to see the beautiful rain  p uq. And it would help with some balancing, because think, just because you go to sleep IRL doesn' tmake the rain stop! And it's just really pretty if this mod is installed on a server :3

**Comment by PitchBright** [comment]
@OreCruncher BetterSleeping does it. Here's reference for how to do it:
https://github.com/CallMeFoxie/BetterSleeping

I work with another guy who coded up a totally configgable Rain/Thunder system for me, back in 1.4.7. We haven't had a chance to update it to 1.7.10 yet though.

Both of these ideas/features, are things that I think would have a better home with this mod here. I can you more details about what my mod did, if you're interested?

**Comment by OreCruncher** [comment]
What I did was essentially redirect the world.resetRainAndThunder() method to one that I created that checks a config option.  This is the method the sleep check during server tick processing calls.

As for other enhancements for Rain and thunder I am interested.  If there is a link to that 1.4.7 mod available I can download and decompile it to see what it was doing.

**Comment by OreCruncher** [comment]
Posted updated mods to CurseForge containing option to disable rain/thunder reset when players sleep: http://minecraft.curseforge.com/projects/better-rain/files.  Applies to 1.7.10-1.0.2.1BETA and 1.8.9-1.1.0.3ALPHA

**Comment by PitchBright** [comment]
No link because it wasn't a public mod. We'll dig up the source for it, and I'll pm it to you or get it to you somehow.
