### ISSUE TITLE
Feature Request: Configurable Light Levels for Rain & Storm

### ISSUE THREAD

**Issue by PitchBright** [OreCruncher/BetterRain#17]
Just an idea I wanted to run by you, as part of the notion that BetterRain would be a better home for yet another little mod I've got on the go. It allows me to configure the Light Level reduction for when it Rains and/or Storms.

Personally I hate that it gets as dark as it does. I don't think "rain" is a very good reason for mobs to start spawning. At least in the context of realism. The mod I'm using now let's me adjust these levels, but it's not quite perfect, and I don't have a lot of time to roll up my sleeves and figure out what needs tweaking… plus I'm not the greatest coder.

**Comment by OreCruncher** [comment]
Light level stuff is a bit voodoo in Minecraft.  I am interested in adjusting light levels based on rain intensity rather than it going dark all the time.  Sometimes it is nice to have a sun shower. :)  I haven't spent time on this as of yet but I have it percolating.

(If you want to share your code so I can see what you have done... :))

**Comment by PitchBright** [comment]
How do I sent you a pm on here? I know you said you don't have skype or any of the other stuff.

**Comment by OreCruncher** [comment]
Not aware of a method to send a PM through github.  If you want to send a PM you can send it through the FTB website - I check there regularly.

**Comment by OreCruncher** [comment]
With the "scale sky darkness" changes BetterRain actually sets the Minecraft rain strength to the generated intensity level.  Minecraft uses rain strength for a number of calculations related to light level and coloration.  By using BetterRain's intensity level Minecraft will use fractional values which will allow "shades of gray" in the sky based on rain intensity.  Low intensity rain has more sun/less fogging whereas high intensity rain will obscure the sun and the sky is a darker gray.

**Comment by PitchBright** [comment]
That sounds pretty good. I look forward to testin' that out.

**Comment by OreCruncher** [comment]
Posted new versions that have the varying sky.  Give it a whirl and let me know what you think: http://minecraft.curseforge.com/projects/better-rain/files

**Comment by PitchBright** [comment]
I like the lightlevel adjustments you've made. Very cool. Closin' this one up. Thanks so much!
