### ISSUE TITLE
[Request] Command to reload biome configuration

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#19]
Currently, in order to update the biome configuration, Minecraft must be closed and relaunched entirely - which, depending on what and how many mods are installed, could take _quite a while_. And it must be done over and over again until the results are satisfactory, and then _again_ for each biome being configured. Having a command to reload the files in-game could reduce the amount of time needed for this process by orders of magnitude.

**Comment by OreCruncher** [comment]
Funny thing I been just thinking about this.  Adding a new feature and I am finding it a pain to start/stop/start throughout the tuning process.

**Comment by OreCruncher** [comment]
Latest BETA version has the reload option: http://minecraft.curseforge.com/projects/better-rain/files
