### ISSUE TITLE
Extra Utilities (and possibly more) mod compatability

### ISSUE THREAD

**Issue by chrisk123999** [OreCruncher/BetterRain#2]
When using this mod and the watering can from Extra Utilities, the watering can won't visually show it's water particles. When it's raining it shows up fine.  So most likely Extra Utilities is using the Vanilla rain drop splash particle for the watering can.  Not sure if it's outside your scope to fix, but would be nice if you can attempt a fix.

**Comment by OreCruncher** [comment]
Yep, this is something as it relates to the mod.  There is rain and smoke particle reduction logic that "thins out" those particles based on rain strength.  Right now the logic applies in all instances, even when it is not raining.  I can improve it by adding an additional "is raining" type check.

**Comment by OreCruncher** [comment]
v0.0.1.7.BETA pushed to CurseForge: http://minecraft.curseforge.com/projects/better-rain/files
