### ISSUE TITLE
[Enhancement] Water wave visuals for ocean/deep ocean biomes

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#22]
The idea is to give the impression of a dynamic water system off the coast.  This effect will apply to ocean, beach, and deep ocean biomes.  Given the nature of Minecraft there may be limits as to what can be accomplished.

**Comment by PitchBright** [comment]
+1 for this idea :)

What about moving stacked water tiles along an axis on beach biomes connected to ocean biomes, (for simplification in the beginning, it could be global… where the Beach biome is (for example) East of the Ocean biome)? 

Layers of water tiles (stacked highest at the anti-node, and lowest near the node, with no stacking on the actual node)…  spawning and despawning, creating the illusion of waves.

**Comment by OreCruncher** [comment]
Though I didn't have that precise idea, my thinking was along the lines of using client side particle effects.  The effects would rise, then subside.  Put these in a chain you get a rolling wave.  Main issue with particles, though, is that Minecraft culls out particles that are over 16 blocks from the player.  They changed this in MC 1.9 to be 32 blocks, but until then....

(Yeah, I could create server side tiles to do this, but then it would affect server side processing, especially given the number of TEs we are talking about.)

**Comment by OreCruncher** [comment]
Looking at how I want to accomplish this this may be a 1.8.9 feature.  My idea is to replace the BlockLiquid rendering routine.  Currently a liquid source block does not fill the entire block space - there is a gap at the top.  My thinking is that for wave motion this gap could be filled/drained based on a deterministic oscillating pattern.  It would be more like ripples than a wave.  Cool thing is that any liquid based on BlockLiquid would get this behavior

**Comment by PitchBright** [comment]
That'd be a lot of block changes for something very subtle, no?

**Comment by OreCruncher** [comment]
It wouldn't be much overhead.  What would be happening is that Minecraft would be calling a Dynamic Surroundings block rendered for liquids rather than using a vanilla one.  Implementation wise I would copy what Minecraft currently does, and then tweak the height value it calculates for the block prior to tessellating.  The reason for the deterministic pattern is that for a given render pass the oscillating motion data could be calculated once, stored, and referred to each time a block renders.  Should be pretty fast.

EDIT: Should also point out that fast trig functions would be used to implement the sine wave pattern for oscillation.  As an example the atan2 function I use for the aurora undulation is based on some fast math from the DSP world.  It's fast, and no one can tell. :)

**Comment by PitchBright** [comment]
Oh that sounds pretty cool!

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
