### ISSUE TITLE
Biome visuals off by one block

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#23]
The biome configuration seems to be applied based on the biome one block east of the player, not the block they're currently standing on. This is very noticeable around biomes with fog effects and background sounds.

**Comment by OreCruncher** [comment]
This with 1.8.9?  Reason I ask is that I don't see a problem with 1.7.10, whereas with 1.8.9 I am seeing some funkiness at the biome boundries.

**Comment by ItsTheKais** [comment]
No, this is in 1.7.10. Here's a screenshot - I'm standing in a Birch Forest M biome, one block west of a Swampland, and I have the green fog and cricket sounds.

![2016-01-19_13 32 36](https://cloud.githubusercontent.com/assets/9879642/12431186/357afc60-beb1-11e5-9b7b-f90fede56d50.png)

**Comment by OreCruncher** [comment]
OK - think I see the issue.  It's the rounding of the player coordinates when I do the check.  Yay!

**Comment by OreCruncher** [comment]
Posted release to [CurseForge](http://minecraft.curseforge.com/projects/better-rain/files).  Fix is in 1.7.10-1.0.2.5BETA / 1.8.9-1.1.0.7BETA
