### ISSUE TITLE
Client crash on log in to server

### ISSUE THREAD

**Issue by rckymtnrfc** [OreCruncher/BetterRain#25]
I just generated a new world on my server but when I logged in I instantly got the following crash.

I generated a new world and the problem is gone but thought I should pass the crash report along.  This is with Forge 1710 and BetterRain beta 6.

http://pastebin.com/qjQZha8T

Thanks!

**Comment by TheDarkPreacher** [comment]
getting same crash (http://pastebin.com/uZsPje0H) how soon will the update get pushed to Curse so the fix can be implemented? Also, might want to message Iskandar about this, he has this mod in his Modular Mayhem Pack. until fix is released, I am disabling this mod in the pack I am playing.

**Comment by OreCruncher** [comment]
Should be posted sometime today.

**Comment by OreCruncher** [comment]
Posted release to [CurseForge](http://minecraft.curseforge.com/projects/better-rain/files).  Fix is in 1.7.10-1.0.2.5BETA / 1.8.9-1.1.0.7BETA

**Comment by rckymtnrfc** [comment]
Thanks for the quick fix!
