### ISSUE TITLE
Rename: Better Rain => Dynamic Surroundings

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#26]
This is to track the work necessary to re-brand the BetterRain mod into Dynamic Surroundings.  Applies to master (1.8.9) and the 1.7.10 branch.

Tasks:
- [x] Publish notice on CurseForge
- [x] Update FTB page information
- [x] External name changes within the mod (mcmod.info, message strings, etc.) and publish

Deep Tasks:
- [x] Change modId.  This ripples into betterrain.json, sounds.json, config files and directory.  Will have user impact.
- [x] Cleanse source code of BetterRain references
- [x] Rename BetterRain Java package
- [x] Test 1.8.9
- [x] Test 1.7.10
- [x] Push new jars
- [x] Rename CurseForge project

Post:
- [x] Update Wiki information

**Comment by atlas6523** [comment]
Quick comment, I think you missed just one aspect of the rebranding.  The GitHub page [name](https://www.google.com/search?q=github+change+project+name&oq=github+change+project&aqs=chrome.0.0j69i64j0l4.5088j0j7&sourceid=chrome&es_sm=93&ie=UTF-8)!  That would require another round of changing links (as in the first 3 tasks).  Just wanted to point this out.  I hope to be a little more active with this mod in the future.  Thanks for all you've done. :)

**Comment by OreCruncher** [comment]
I purposely left it alone.  Changing it would break other links to the site.
