### ISSUE TITLE
[Enhancement] Improve clouds

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#29]
Get away from the blocky clouds to something a little more realistic and that responds to weather intensity.  The clouds in Weather2 is a good example.

**Comment by ItsTheKais** [comment]
Realistic clouds aren't a good idea - this is _Minecraft_ we're talking about. "Blocky" is the name of the game. The clouds in Weather2 look horribly out-of-place in a game like this, not to mention they're needlessly resource-intensive.

Have you seen [this](http://i.imgur.com/Dqit8.gifv) before? I've always thought this was how Minecraft's clouds should work. This could be adapted to the weather system by adjusting the brightness threshold when converting to black and white in the last step.

Another idea to consider: more than one cloud layer, possibly reacting to the weather and the landscape below in different ways.

**Comment by OreCruncher** [comment]
I was thinking more realistic in terms of how they behave rather than any particular rendering style.  The cool thing about the existing Minecraft clouds is that it is a simple texture that is rendered at some Y in the world.  Quick, easy, little processing.  The main challenge with altering clouds is doing it in such a way as to not incur rendering performance issues when not using shaders.  If a player truly wants realistic clouds that is the direction they should look (shader mod with appropriate cloud shaders).

Whatever form this takes the player will always have the option to turn on/off.  As you point out players may want cuboid looking clouds rather than volumetric/puffy clouds.  Also, it would be possible to provide several different cloud rendering mechanisms so the player has a choice as to how they want their clouds to look.

**Comment by OreCruncher** [comment]
Been mulling this a bit.  I think the first approach I want to try is changing the current cloud texture and introduce multiple cloud layers as @ItsTheKais suggests.

Another possibility I want to mention here so I don't forget is to make the cloud layer 3D.  Right now clouds render as a single sheet.  The idea is to stack multiple sheets on top of each other to give a clouds a 3D effect.

**Comment by OreCruncher** [comment]
Running into clipping issues related to multi level clouds.  Need to do more research.  Until then, I have changes that will adjust the cloud layer up/down based on dimension settings as well as darken the clouds themselves based on storm intensity.

**Comment by OreCruncher** [comment]
Posted an update to CurseForge: http://minecraft.curseforge.com/projects/dynamic-surroundings/files

**Comment by PitchBright** [comment]
@OreCruncher awesome!! I was just about to FR some things on clouds. Darkness being one of them.

Is cloud opacity in this mix too, or should I open a request for that?

**Comment by OreCruncher** [comment]
How would opacity function with the clouds?  Looking for something that simulates some sort of cloud density?  If so that could be something I tackle when I look at providing a mod specific cloud renderer.

**Comment by PitchBright** [comment]
I was just thinking a simple opaque:true/false option. I hate that mojang clouds are translucent, so I thought I'd float the idea of allowing the user to make 'em opaque. If that's easy & do-able?

**Comment by OreCruncher** [comment]
Without creating a cloud renderer or using ASM to modify the java code on the fly? No.  The best approach would be to create a custom renderer and hook that into the cloud rendering system.  When I get to that point my thought was to start with the existing Minecraft renderer and massage into what I want.

**Comment by PitchBright** [comment]
Ah dang. I was hoping it was an easy thing… even if only implemented temporarily. S'all good.

As an aside… I've been thinking about the way clouds are currently executed, using that noise texture sheet. I forget what layer they appear on… something around 115'ish I think. Anyway, it got me wondering if there's some merit to the idea that there could be a whole range of layers, each with their own texture sheet. This would allow clouds to take on Cirrus and Cumulonimbus and Stratus etc etc, shapes… if the pixels on the textures sheets were crafted to layer up in such away to create that illusion of vertical density/depth/height.

I've heard people say clouds cause lag, though I've not experienced that… I'm sure if the current single-layer clouds are killing FPS for some people… a multi-layer system wouldn't be friendly to them. (But screw those people, lol).

**Comment by OreCruncher** [comment]
I did try messing around with having 5 layers of cloud, one stacked on top of each other.  Each layer would have been offset by a different amount to give it a 3d type feel.  In general it did what I wanted to do, but I didn't like the result.  Clipping became an issue (and to be fair it is probably due to my lack of knowledge), and the clouds looked too tubular.  However, I think the approach is sound - just needs a different set of textures to do this.

When I get back to this my plan is to make a 3D noise data set to generate multiple different cloud layers to see how it works out.  May be able to actually generate the texture(s) on the fly using a background thread.  If I could do it on the fly I could have the storm intensity influence the shape/volume of the clouds in real time.  Right now this sounds great on paper, but I have not done anything like this before so I may be a bit naive. :)

**Comment by PitchBright** [comment]
Sounds to me like you're a step or two ahead meh. Probably turned out tubular if you were using the same sheet for each layer, ya?

I could always try and whip you up some layer variations in photoshop if you wanted to play around a bit more with it. Plus I'd love to see some screencaps of it in action. I've been picturing it in my head for years. I want to scream "It's aliiiiive".

https://www.youtube.com/watch?v=xos2MnVxe-c

**Comment by OreCruncher** [comment]
lol.  If I can get it to work in real time there wouldn't be a texture - it's dynamically created based on real time information.

**Comment by PitchBright** [comment]
No i meant for your previous method. The real-time gen sounds pretty awesome too.

**Comment by OreCruncher** [comment]
Yeah - using the same texture sheet for each level isn't the way to go.  Ideally each sheet should relate to each other - it's why I am looking at the 3D noise approach.  It would be possible to generate several static layers using a graphic tool to accomplish this, but then you wouldn't be able to make the clouds dynamic.

**Comment by PitchBright** [comment]
True dat.
