### ISSUE TITLE
[Enhancement] Rainbows!

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#3]
Spawn rainbows in "warm" climates when rain stops.

**Comment by PitchBright** [comment]
A big +1 :)

**Comment by O13SC3N3** [comment]
Probably can achieve like the auras with the conditions bright daylight 10amto2pm ish with light rain intenisity.

**Comment by OreCruncher** [comment]
I could do something similar.  An aurora has 1 vertical band where OpenGL does a gradient fill between two colors.  For a Rainbow I will need 7 different vertical bands, each having a start and end color.  The other question is whether the wavy undulating look is OK for the rainbow, or should I make it more a flat band.

**Comment by PitchBright** [comment]
Flat for sure.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
