### ISSUE TITLE
[Enhancement] Lava vs. water == steam

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#32]
One thing that has bothered me is that lava can be near water but not generate steam.  This aims to address that. The idea is that a water source block can spawn a steam jet if near lava.  Would behave similar to a fire jet, but give off white puffy particles simulating steam and some amount of hissing.

**Comment by PitchBright** [comment]
Very cool

**Comment by OreCruncher** [comment]
Posted CAVERNS BETA: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
