### ISSUE TITLE
Auroras won't behave themselves after latest update

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#36]
Following the move to dimension json files, auroras don't seem to respond to changes in the various height values anymore. I've tried changing both `cloudHeight` and `skyHeight` to above 256, but they are still showing up far lower than they should be and clipping into ATG's mountains.

**Comment by OreCruncher** [comment]
Can you provide the json for the dimension you configured?

**Comment by ItsTheKais** [comment]
```
{
    "entries":[
        {
            "dimId":0,
            "seaLevel":64,
            "skyHeight":256,
            "cloudHeight":256,
            "haze":false,
            "aurora":true,
            "weather":true,
        }
    ]
}
```

**Comment by OreCruncher** [comment]
Remove the comma at the end of the "weather" line.  If you look at the Forge log output you should see the Json parser having some issues with the file.  I put the corrected Json in my test config and it appears to work.  Let me know.

**Comment by PitchBright** [comment]
@ItsTheKais here's a handy site for checking your JSON files, to make sure you've formatted them correctly before using them… check it out: http://jsonlint.com

**Comment by ItsTheKais** [comment]
Okay, I've fixed the json file, but I'm still not seeing any changes. What values should I be using for `skyHeight`/`cloudHeight` in order to move the auroras above the build limit?

**Comment by OreCruncher** [comment]
Did you set "Height Player Relative" to false in the dsurround.cfg?  The cloudHeight of 256 should put it much higher up in the sky - just above normal build height for Overworld.

**Comment by ItsTheKais** [comment]
Height Player Relative is indeed false.

EDIT: fixing the json had actually solved the problem. I had set the biome I was testing in to have more fog than usual and forgot about it, so I couldn't see the auroras above me (and assumed they were still buried under the mountain).

Sorry for the wild goose chase.
