### ISSUE TITLE
Perhaps make an option for the elevation haze to cap at a certain height

### ISSUE THREAD

**Issue by jurplel** [OreCruncher/BetterRain#38]
If someone wanted to build a base very high in the sky, even if fog was at 0.05, you couldn't see the ground at all.
Haze Factor at 0.05 at y=200: http://i.imgur.com/yeeG48W.png

**Comment by OreCruncher** [comment]
I have been thinking about that as well.  My thought is that it would be more like a band around cloud height where it gets dense as you go up, but when you pass cloud height it becomes less dense again.

**Comment by jurplel** [comment]
Sounds good to me.

**Comment by OreCruncher** [comment]
Posted an update to CurseForge that has elevation haze operate in a band at cloud height: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
