### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by DadYoshi** [OreCruncher/BetterRain#39]
Crash report attached
[crash-2016-01-27_20.42.10-server.txt](https://github.com/OreCruncher/BetterRain/files/108854/crash-2016-01-27_20.42.10-server.txt)

**Comment by OreCruncher** [comment]
Thanks!  When does this crash occur?  Start up, launching world, running around doing stuff then it crashes, etc.

**Comment by OreCruncher** [comment]
The CAVERNS BETA release for Dynamic Surroundings will have defensive code in place.  What appears to be happening is that the player biome is being reported as one that did not exist in the biome table when it scanned Forge/Minecraft.  One of the mods could be adding a biome late in the mod initialization process which could be triggering the problem.

**Comment by OreCruncher** [comment]
Posted CAVERNS BETA: http://minecraft.curseforge.com/projects/dynamic-surroundings/files.  If possible give it a try and let me know how it goes.  If it works, could you provide a link to the latest client forge log so I can take a look?  I added some additional debug trace to try and figure out what Minecraft is thinking.

**Comment by DadYoshi** [comment]
Will do.

**Comment by DadYoshi** [comment]
It seems to be working now.  Here is the log.
[fml-client-latest.txt](https://github.com/OreCruncher/BetterRain/files/111025/fml-client-latest.txt)

**Comment by OreCruncher** [comment]
Glad it is working.  Nothing is showing up in the log and I expected to see something.  Maybe it is some sort of transient issue that popped up.  If you have any further problems let me know.
