### ISSUE TITLE
A plague of falling rock noises on your superflat worlds!

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#44]
The underground biome detection might need a "can't see the sky" check...

**Comment by OreCruncher** [comment]
I will look into it.  I use the sea level value reported by the dimension to see if it is underground.  Superflat provider may be doing something strange.

**Comment by OreCruncher** [comment]
Yeah - the average ground level reported when superflat is 64.  So I have to splice in a workaround when superflat.

**Comment by OreCruncher** [comment]
Posted an update to CurseForge that fixes Overworld sea level to y=0 when it is a SuperFlat world: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
