### ISSUE TITLE
Aurora height too low, intersecting with blocks

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#5]
When set to a fixed altitude, auroras intersect blocks near the top of the world, which is particularly noticeable with non-default terrain generators such as ATG and vanilla amplified. The Y-level auroras appear at should be raised so that they are above the maximum buildable height.

![2016-01-07_17 28 06](https://cloud.githubusercontent.com/assets/9879642/12186901/466b60b0-b564-11e5-978d-8d50121522e1.png)

**Comment by OreCruncher** [comment]
I am working on a set of changes that will allow a player to customize sea level and sky height because of mods like ATG.  They like making really tall mountains, which is cool, but the height of those mountains are way past cloud height and right up against sky height (the max build height).

By default I do not want to make the Auroras spawn too much higher.  Reason is that a player would have to be looking way up to see it rather than having it show up just above in the top part of the screen if they are looking north.

EDIT: NVM - reread and saw where you changed the relative Aurora.

**Comment by OreCruncher** [comment]
Release out on CurseForge that allows tuning of dimension sea level and sky height parameters: http://minecraft.curseforge.com/projects/better-rain/files

**Comment by ItsTheKais** [comment]
I'm sorry, I think there's been a misunderstanding... the latest update has support for the height of player-relative auroras, but I was referring to _non-relative_ auroras. With `B:"Height Player Relative"=false`.

**Comment by OreCruncher** [comment]
No, I think I understood.  Player relative auroras are fixed at 64 blocks above the player.  It maintains this distance regardless of the players Y value.  If the player flies up they will never reach the aurora.  This is the default.

World relative auroras are fixed at a specific Y in the world, which is just above the cloud layer for the dimension.  If the player flies up the aurora gets closer and eventually the player will be able to "touch it".  This is what you have in your screen shot.  You flew above the aurora and looked down at it.

The settings I put into the mod allow the player to override what Better Rain thinks is the sea level (provider.getAverageGroundLevel()) and sky height (provider.getHeight()).  By default Overworld reports an average ground level of Y=64, and sky height of Y=256.  Cloud level is half of sky height, or Y=128.  In your case if you are using ATG and want to avoid what you see in your screenshot you would have to edit the config and put in something like "0,64,1024".  By setting a sky height of Y=1024 BetterRain thinks the cloud layer is at Y=512 (half of 1024).  The effect would be placing the aurora at 4x the default height.

In general, though, sticking with player relative auroras is easier to deal with.  I even put in a config option to change the fixed distance to maintain if you want it a bit higher.

**Comment by ItsTheKais** [comment]
Okay, I see now. I was looking in the wrong place for that sort of setting. Thanks for the help, and sorry about the confusion.

**Comment by OreCruncher** [comment]
No worries. :)
