### ISSUE TITLE
[Enhancement] Dripping leaves after rain

### ISSUE THREAD

**Issue by novasolarius** [OreCruncher/BetterRain#52]
I would eventually like to see water dripping off leaves during and after heavy rainfall. A bit like the particle effect that occurs on the bottom of a block when there's water or lava on top. This would (for obvious reasons) have to be limited to leaves that are actually hit by said rain. I'm not sure if that would actually be possible (almost sure though) or reasonable (might cause a bit of lag in forests), but I feel like this would be neat.

Thank you for reading, keep up the amazing work.

**Comment by OreCruncher** [comment]
This would be an interesting idea.  As you point out lag can be an issue.  I will have to think about this a bit.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
