### ISSUE TITLE
Sounds that play randomly when you step on specific blocks

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#53]
Would it be possible to add a few sounds that have a chance to play if you step on specific blocks?

Some examples could be leaves rustling if you step on leaves, screaming if you step on soulsand, and so on.

**Comment by OreCruncher** [comment]
It should be possible.  Right now I am looking at player sounds - sounds that generate based on player activity.  In this example the activity would be "standing on a block".  Redstone ore responds to this by lighting up but there is no reason it couldn't play a sound.

**Comment by OreCruncher** [comment]
These sounds - they would be considered spot type sounds rather than something that plays continuously?

**Comment by Sunconure11** [comment]
Yes. You wouldn't soul sand to scream at you every time you step on it, would you?

**Comment by Sunconure11** [comment]
Other sounds in this direction:

Creaking wood
Rocks tumbling
Rocks being kicked
Gravel and sand being kicked up
Low, resonant sound from end stone (think stuff like whale song or even reconstructed hadrosaur songs (https://www.youtube.com/watch?v=d-tRFuMdQkA), but, more... eerie)
Hissing in grass and flowers
Labored breathing from Nether Bricks (Maybe we can make the nether just as creepy as it is in MATMOS)
Crawling in silverfish-infested stones, plus hissing
Mud being kicked up (only plays in non-oceanic biomes and if you are stepping on dirt while underwater)

Sounds that would always play:

Crops and plants rustling (also has a random chance of playing even if not stepped on to simulate wind)
Ice skidding (plays always if you run on ice)
Papers rustling (if you step on a bookshelf, also might play in abandoned buildings with bookshelves at random)

**Comment by O13SC3N3** [comment]
Don't forget MATMOS got beyond reasonable in modpacks cuz the amount of lag it produced.

**Comment by OreCruncher** [comment]
Having them work as spot like sounds is much easier and makes more sense.  It's what I was originally thinking but wanted to make sure you were thinking the same thing. :)

And I do worry about lag every time I change something.  What makes this mod different from others like MAtmos and Ambiotic is that I don't do block scanning to try to figure out the most "optimal" way of doing something.  I follow the "good enough" rule. :)

As it relates to this particular feature it should be straight forward to implement.

**Comment by OreCruncher** [comment]
Have step sounds for wood planks/stairs, gravel, and stone.

**Comment by OreCruncher** [comment]
Started [#56] for sound suggestions

**Comment by OreCruncher** [comment]
Pushed BETA to CurseForge
