### ISSUE TITLE
[Enhancement] Add air quality ala Enviromine

### ISSUE THREAD

**Issue by Ambientmaple** [OreCruncher/BetterRain#55]
Could you add Enviromine support like when there is a sandstorm in the desert Air Qualtiy decreases. That would be awesome to have in a hardcore pack, Thanks

**Comment by OreCruncher** [comment]
Right now the focus is on client side visuals and sound.  No plans at the moment for changing the actual game mechanics.  I will leave this here in case I change my mind. :)

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
