### ISSUE TITLE
Player crashed upon entry to a server with this mod

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#59]
A player tried to enter my server using this mod, and crashed with the following error:

http://pastebin.com/7j4ZCHXn

**Comment by OreCruncher** [comment]
_Grumble_  The sound is down in the sound system and apparently Minecraft's layer on top of it lost track of the sound. _sigh_

**Comment by OreCruncher** [comment]
Is the player dead in the water or can the client start?

**Comment by Sunconure11** [comment]
It happens when the player tries to enter the server. I'm not encountering the issue myself, but, another user is.

The client is fully booted when this happens.

**Comment by OreCruncher** [comment]
Right, but it is _always_ happening vs. sometimes happening?  If it is always happening they can turn biome sounds off for now until I can make Minecraft behave.

**Comment by Sunconure11** [comment]
It is always happening.

**Comment by Sunconure11** [comment]
http://pastebin.com/kssrGgDi

Yet another player crashed with a similar error.

**Comment by OreCruncher** [comment]
OK - same root problem.  I should have a private build real soon with some changes that should address.  I will make it available for the players to give it a shot and report results.

**Comment by OreCruncher** [comment]
Have them try this release: https://github.com/OreCruncher/BetterRain/releases/tag/v1.7.10-1.0.4.4BETAHF

**Comment by Sunconure11** [comment]
I will post the results of this soon.

**Comment by Sunconure11** [comment]
Crashing appears to have stopped

**Comment by OreCruncher** [comment]
Thanks for letting me know.  I will be posting another "official" release a bit later.

**Comment by OreCruncher** [comment]
Posted a release with the fix: http://minecraft.curseforge.com/projects/dynamic-surroundings/files

Let me know if it holds.

**Comment by OreCruncher** [comment]
@Sunconure11 any feedback with the patch?

**Comment by Sunconure11** [comment]
It works

**Comment by OreCruncher** [comment]
Thanks for the feedback.  The next BETA will have a better fix for what I as trying to address (a sound stopping before it's time).
