### ISSUE TITLE
Fog returns to default when under a roof

### ISSUE THREAD

**Issue by ItsTheKais** [OreCruncher/BetterRain#61]
The view from right in front of a building:
![2016-02-06_17 18 49](https://cloud.githubusercontent.com/assets/9879642/12870173/0db19c22-ccf6-11e5-9f09-fdc7f9b95b0b.png)

If I take a step back so I'm under the overhanging roof:
![2016-02-06_17 18 45](https://cloud.githubusercontent.com/assets/9879642/12870176/1ccc7bfa-ccf6-11e5-8329-32a4a2cfa0b7.png)

Going in and out of buildings frequently makes the atmosphere a little bit spasmodic, with the fog zooming out and back in and cycling between blue and brown over and over again.

**Comment by OreCruncher** [comment]
Yes.   Right now I do not have a good solution.  When you are inside a building you are actually in the "Inside" fake biome that does not have dust, fog, etc. attached to it.  What you are experiencing is the fade in/out when transitioning biomes.  The reason for the "Inside" biome is so when a player builds a structure, or is in a structure, in a desert biome the fog shouldn't be present on the inside.

(Inside is defined as having 50%+ blocks above the players head in an area.  Your overhang plus the buiilding behind you matches the 50% requirement.)

**Comment by OreCruncher** [comment]
I changed how things work with "inside".  As a result:
- No more Inside biome.
- When calculating fog effects a ceiling coverage ratio is generated.  This ratio determines a distance offset for the fog.  The higher the ratio, the more distant the fog line starts.
- Biome sounds will no longer play when a player is considered "inside" (ceiling coverage of about 50%).  This is hard coded.

So, how does this work.  When 100% covered by blocks the fog line starts 15 blocks further away.  This gets the fog out of the structure, which is what I am wanting.  If standing outside under the eave of the building coverage is roughly 50% meaning the fog line is pushed out 7 blocks (i.e. it gets foggier).  0% ceiling coverage means normal fog effect.

This change will be in the next BETA.

EDIT:  Should also point out that if you look out a window in a structure the fog will be there preserving the ambiance.  It's just rendered a little bit further away.

**Comment by OreCruncher** [comment]
Posted BETA with this change: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
