### ISSUE TITLE
[Enhancement] Windows fogging up from snow, rain or steam

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/BetterRain#62]
Is this even possible? This just popped in my head.

**Comment by OreCruncher** [comment]
That indeed would be interesting.  Also applying a bit of frost to windows in a cold climate.  Honestly I don't know.

**Comment by AlienXtream** [comment]
best thing i can think of would be to use an overlay plane on the glass but that could get laggy with large glass constructions

**Comment by OreCruncher** [comment]
Yeah - it's what I was thinking.  A second pass overlay of some sort.

**Comment by Sunconure11** [comment]
If this is added, what about some way for players to clear off fog or steam manually?

**Comment by OreCruncher** [comment]
To allow a player to clear fog off a window would require state to be kept somewhere.  Not impossible, but it can get complicated.

**Comment by Sunconure11** [comment]
I see.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
