### ISSUE TITLE
[Enhancement] Probability control on Auroras

### ISSUE THREAD

**Issue by PitchBright** [OreCruncher/BetterRain#7]
It would be great to be able to make Auroras an "event", rather than a nightly occurance… via probability control in the config file. If that's easy enough to do?

**Comment by OreCruncher** [comment]
I will have to think on this.  I would have to have some sort of time memory in the process and right now it is not set up to do that.

**Comment by PitchBright** [comment]
Thanks, that'd be wicked! As it stands now, I can see the novelty wearing off after about 5 minecraft nights in a row, on the server. I know if I could set it to be more of a rare occasion type-thing, it will always be a treat to catch "the lights at night".

**Comment by OreCruncher** [comment]
Doing some reading - maybe instead of probability have them spawn when there is no or little moon.  A lot of "background light" could obscure an aurora and I figured a moon that is lit could cause this.  Doing it this way is much simpler than generating/tracking probabilities.  I would also think it would work well with other mods that generate custom dimensions with/without moons and the like.

**Comment by PitchBright** [comment]
The "background light" is actually something I wanted to talk with you about. You got an IRC channel or discord, skype, teamspeak?

**Comment by OreCruncher** [comment]
Sorry, don't have any of those communication methods.  I did push a build to CurseForge that further limits aurora spawn to nights where there is a quarter or no moon.  I would like to avoid probabilities at the moment because of how things are structured.

**Comment by PitchBright** [comment]
I haven't seen an Aurora since the first night on the server, when I originally added the mod. Can you take a look at my config and see if I'm doing something stupid?

http://pastebin.com/fdKtadmL

**Comment by PitchBright** [comment]
Edit: Not true… since the latest update, I think.

**Comment by OreCruncher** [comment]
What phase is the moon in?  For an aurora to spawn it needs to be less than half full.  (The config file looks fine, and I am going to assume you haven't messed around with the biome configuration.)

**Comment by PitchBright** [comment]
Less than half full (I'm assuming both on the waxing and waning sides)? I guess that's one way of making aura's more rare in vanilla… but at that point, you might as well just set 'em to spawn only half the time… and do away with the moon-logic because I'm pretty sure Auroras aren't tied to the phase of the moon in reality.

As for using it with Stellar Sky mod… tying it to the moon phase like that will give you completely different results than what you'd get in Vanilla, because the phase of the moon in StellarSky is literally calculated by the angle of the moon and the sun relative to earth. The moon has it's own cycle through  the sky and isn't rigidly set at being opposite the sun, like Mojang's logic.

**Comment by OreCruncher** [comment]
Actually it is tied to the brightness level of the moon, not specifically the phase (`world.getCurrentMoonPhaseFactor()`).  When I mean by less full the brightness is < 0.5.  For regular Minecraft that means the moon is 1 quarter (waxing or waning) or new.  The reason it is tied to brightness is because in general auroras are visible when background lighting is less.

(BTW, the call to getCurrentMoonPhaseFactor() under the hood calls in to get the actual moon phase so it can index into a table to return the brightness factor.)

**Comment by OreCruncher** [comment]
A thought I had was to scale the visibility of the aurora based on the brightness of the moon.  Internally I would change the alpha (transparency) value of the aurora based on moon brightness.  A full moon would have a 100% reduction (invisible) whereas a new moon would have no reduction.  The benefit of doing it this way is that I kinda get what I was looking for (visibility of the aurora affected by moon brightness), and it allows a mod like StellarSky to manipulate the moon brightness for it's own purposes and have it affect aurora rendering (assuming the author wishes to do this).

**Comment by PitchBright** [comment]
Hmm, but if ya do it that way it's still sorta the same thing, instead of Auroras 50% of the time, based on moon phase, you've got Aurora brightness based on moon brightness… and the moon's always got some brightness IRL (except that perfect New Moon moment)… so what happens then is you end up with Auroras all the time again, but then tied to other unrelated mechanic to determine it's aesthetics. I think that's moving towards a bigger house of cards, to be honest.

(I do like the idea of you making Auroras transparency vary with each spawn though, especially if you make the min's and max's configgable)

I recently redid all the algorithms for the way Stellar Sky illuminates, fades planets and the moon and scintillates stars, based on the sun's position… including the moon's phases and brightness-magnitudes working with alpha… so I got to know Abastro pretty well… he's a stickler for realism as much as I am (we still squared off over whether or not brighter stars twinkle more than dimmer stars, in a uniform manner, when factoring air turbulence, lol). Anyway, I think it's safe for me to say he wouldn't go for tying the moon to it that way, if he was given the choice. If I pitched the idea to him, like it was my idea, he'd retort that aurora occurrence isn't related to the moon at all. Then he'd probably try to find a way to (if he hasn't already) to put phases on the Sun in for the purposes of being the mechanic that trigger Auroras, using the player's latitude as some kind of factor in the equation. I know he had plans to do Auroras, but it may not be necessary with BetterRain in the picture handling them. Now that I think about it, I'll pick his brain on the SunPhase + Latitude idea anyway, maybe he'll make that available in a method so that you could call it, for your BetterRain + StellarSky users.

I'm digressing a bit… anyway… maybe we went down this path because I didn't understand your first response about needing time-memory in the process. What I was originally thinking is, if you've got already got a mechanism that determines "if" an aurora is spawned, then maybe if you just add some kind of "if (probabilityConfigValue > random.nextFloat())" type thing in there in front of it (or maybe after it) when it makes the "should it spawn" check, that would be a pretty easy solution giving the user the flexibility to control how often an Aurora is a treat. Yes/No?

**Comment by PitchBright** [comment]
Oh… btw. I do understand the logic behind your idea of the visibility of the auroras being affected by the moon's phase, and I'm a proponent of the idea, but really more so in the context of as a supplemental thing. As a visibility "factor".

Mostly because the moon's phase/brightness can be roarin' full tilkt at Full Moon, but the moon not be visible because it's position is below the horizon. We're already digging into a solution for that for the HardcoreDarkness mod that manipulates the darkness/gamma levels of night visibility based on MoonPhase… because we're seeing that the ground is illuminated like there's a full moon, even when the full moon isn't "up in the sky".

**Comment by OreCruncher** [comment]
In terms of RL auroras my impression is that they are _always_ there - its just a matter of how intense it is (i.e. energy involved - that is where things get complicated based on sun, etc.) and whether the light emitted by the aurora can overcome the atmospheric environment (sunlight, background light, etc.) and locale (latitude) so a viewer can see it.  There are some areas where humans live where they can see the aurora every other day (on average).

As for a hook, something like "getAuroraIntensity()" or some such would be cool.  I could have a basic method in BetterRain that does something simple, but if StellarSky is installed I could use that and it can perform whatever magic it needs to do the calculation.  At this point, though, he should probably pull out the aurora code from BetterRain and integrated it with StellarSky - my mod is licensed MIT so he can do that freely.  If that is something he doesn't want to do at the moment, if you/he could whip up a formula for calculating an OpenGL alpha value it would be cool.  Let me know and I can give the particulars of aurora alpha behavior.

As for the random aurora event there may be some things I could do to determine if auroras spawn for a particular night.  I now have a mechanism in place to record world state and I could put markers in that data.  Reason I that I need to have that knowledge between server ticks as well as for when the server restarts.  It then becomes a question then as to what a good value for random spawn will be.

**Comment by PitchBright** [comment]
I didn't know about the "always there" thing. I shoulda looked into that before I shot my mouth off. I'll do a little research, I know Abastro will totally call me out for not knowing the dealy-oh on that stuff, when I bring it to the table.

I'm probably not understanding how you've setup the spawning, or the idea behind a 'particular night', because i'm not really a strong coder. More of a math and game-design guy. Maybe I'm over simplifying my idea with a 0%-100% chance of the spawn event being added/included/occurring.. and aurora spawning can't work that way? I'll admit I haven't looked at the code to see how it all works.

**Comment by OreCruncher** [comment]
I have been reading up on auroras recently because of all this.  I kinda new some of the whys/wherefores, but nothing in detail.  Learned more than I wanted - enough to know that to make auroras mimic real life would entail quite a bit of other stuff - like StellarSky. :)

In terms of "having a memory" about auroras is pretty simple.  Right now it does some work per tick, and once the tick is over it forgets about it.  So if I were to make things random, it would do the random check one tick, and then will try to do it again next tick because it doesn't know what happened in the tick prior.  To do this random thing I would have to store data somewhere that says "did the check already for the current night, so don't do it again".

"Spawning" is the word I use to describe the internal mechanics.  Spawning actually implies that the server sends out data to all attached clients, and the clients do some bookkeeping on their end to track and render.  Spawning is a big deal because if an aurora doesn't have to display the server doesn't send out packets to clients, and clients don't have to worry about rendering.

With the current implementation RE: moon brightness if the brightness is < 0.5 or being day BetterRain doesn't waste cycles generating/broadcasting aurora information.  It essentially skips that tick as efficiently as possible.

**Comment by OreCruncher** [comment]
The release version of the mod uses the moon brightness as a factor for calculating the alpha used to render the aurora.  With a full moon the alpha is at it's lowest so it doesn't show, and at a new moon alpha is at its greatest meaning highly visible.

**Comment by PitchBright** [comment]
I'm on 1.0.4.7BETA… I'm just about to update to 1.0.4.10

I'm still not seeing auroras. I don't think I've seen one since the last time I mentioned seeing one. I also notice that the list of biomes that auras can spawn in has been removed. Is it locked to polar biomes now?

**Comment by PitchBright** [comment]
Hm, just noticed the Wiki.

https://github.com/OreCruncher/BetterRain/wiki/Biome-Configuration

Do I need to configure all the biomes that I'd like auras to spawn in? That'd probably explain why I'm not seeing any because I have this in my config:

biomes {
    # Configuration files for configuring Biome Registry [default: ]
    S:"Config Files" <
     >
}

**Comment by OreCruncher** [comment]
What biome are you in?

**Comment by PitchBright** [comment]
We've played across countless biomes, in the past 2 months.

I whipped up a json for biomes=.\* auroras=true, and updated the mod. I'll see if that makes a difference.

If not, my best guess is that it's related to aurora's needing "moon brightness < 0.5", and Stellar Sky keeping the moon brightness above 0.5 most of the time, given the orbit of the moon.

**Comment by OreCruncher** [comment]
So there isn't a "new moon" with StellarSky?

**Comment by PitchBright** [comment]
There is, but it's pretty rare that it's up at night.

**Comment by OreCruncher** [comment]
That is probably it, then.  I scale the alpha value based on the [brightness of the moon](https://github.com/OreCruncher/BetterRain/blob/master/src/main/java/org/blockartistry/mod/DynSurround/client/aurora/AuroraRenderer.java#L57).  Auroras are at their brightest when "new moon", and it is non-existant at full.

**Comment by PitchBright** [comment]
I was reading up about Auroras and Full Moons, some photographers prefer shooting them at that time actually. 

Maybe Aurora visibility can be reduced by only 50%, during Full Moon or something?, so it's not an inverse 1:1 relationship.

Even then, I think I'm more convinced now than ever, that tying it to the moon phases, isn't a great solution... as far as finding a way to make them less "frequent" goes. Do we have any other ideas about how to give more config/control to the user for their frequency?

**Comment by OreCruncher** [comment]
As mentioned in discussion prior they are always there - its a matter of whether they can be seen because of all the ambient light factors.  I recently saw some pictures taken from space of the borealis over areas that do not see them except for rare occasions.  My thinking RE: moonphase is that it would be the ambient light factor for visibility.

Based on this discussion as well as players having "problems" finding an aurora I am inclined to remove the light factor calc.  Keep things simiple.  Of course this means that players will always see them from polar biomes regardless of light.

I could spend time making them "random" (either truely or deterministic based on factors such as world seed).  I am not sure that the introduced complexity would be worth it.  I will have to think on it further.

**Comment by PitchBright** [comment]
So right now in the code… Aurora's are pretty much perpetual, but the player will only see one if:

1) It's night
2) The moon's brightness not drowning them out
3) Player is in a Polar Biome (hard coded?)
4) Player is in a json configged biome for aurora
5) There isn't another aurora (or was it two?) in existence

Am I understanding that correctly?

**Comment by OreCruncher** [comment]
Almost - some clarification:
3. It's tied to the biome record.  The default biome selection rule is:

```
{
            "biomeName":"(?i)(.*taiga.*|.*frozen.*|.*ice.*|.*tundra.*|.*polar.*|.*snow.*|.*glacier.*|.*arctic.*)",
            "aurora":true
}
```

A player configured Json can override this, or include other biomes.
5. IIRC there is a 400 block distance between auroras.  It's hard coded.  So in theory there could be an infinite number of auroras, though from a practical sense that would be impossible.  If all the players on the server were in polar biomes, and each player was at least 400 blocks from each other, then each would cause an aurora to spawn.

**Comment by PitchBright** [comment]
1. okay cool cool
2. gotcha thanks

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
