### ISSUE TITLE
VAT crash on Chicken sound splash?

### ISSUE THREAD

**Issue by fwsGonzo** [OreCruncher/BetterRain#71]
It's abit tricky for me to figure out what really happens here, but:
Thaumcraft VAT with vanilla Chicken with healing vial --> Dynamic Surroundings heal splash --> Crash

https://gist.github.com/fwsGonzo/d91ddd451854cf188e34

Can I use forge option to get rid of the erroring entity?
What do?

**Comment by OreCruncher** [comment]
Set "Damage Popoffs" to false in your config - should do the trick.  Looks like the event coming through the event system has bad data in it.

**Comment by fwsGonzo** [comment]
:+1:

**Comment by OreCruncher** [comment]
Posted BETA with a fix: http://minecraft.curseforge.com/projects/dynamic-surroundings/files. You can turn the pop offs back on. :)
