### ISSUE TITLE
Ambient sounds play while the game is left paused

### ISSUE THREAD

**Issue by jurplel** [OreCruncher/BetterRain#72]
Sounds stop playing when you pause the game during a sound, but if you leave the game paused then sounds occasionally play.

**Comment by O13SC3N3** [comment]
Which sounds have you noticed with this? And in the console are their any errors?

**Comment by jurplel** [comment]
Cave sounds, and no errors

**Comment by O13SC3N3** [comment]
Kk I'll try to confirm this for @OreCruncher

**Comment by O13SC3N3** [comment]
So I can't personally confirm this, I useally have a resource pack for bient cave sounds as well. Disabling it I am still able to experience dynamic surroundings with out issue in regards to the op. You have anything else that could add elements to your world with sounds?

**Comment by jurplel** [comment]
It doesn't affect the playing of sounds, it's just that if you leave the game paused, it plays sounds from dynamic surroundings (not just cave sounds)

**Comment by jurplel** [comment]
Also they are definitely the ones from Dynamic Surroundings

**Comment by O13SC3N3** [comment]
@OreCruncher I really don't see how your mom would bypass the game engine being paused? But maybe lol?

@jeep70 this in single or multi? Some launchers like multimc is know to create a server environment so somethings could stay active?

**Comment by O13SC3N3** [comment]
Mod+

**Comment by jurplel** [comment]
I am using MultiMC

**Comment by O13SC3N3** [comment]
What version of mod and forge you are using? I am going to test that environment see maybe it's specific

**Comment by jurplel** [comment]
Dynamic Surroundings 2.0.4.6BETA, Forge 11.15.1.1722. I also have Sound Filters (among others) if that might make a difference

**Comment by O13SC3N3** [comment]
Like what Sound Filters?

**Comment by jurplel** [comment]
http://minecraft.curseforge.com/projects/sound-filters/files/2224005

**Comment by O13SC3N3** [comment]
You can try disabling the mod sound Filters and see if its solves. And do the same with it enabled and dynamic surroundings disabeled. See if the issue exist as well with sound Filters.

**Comment by jurplel** [comment]
Issue exists with no mods other than dynamic surroundings

**Comment by OreCruncher** [comment]
Any sounds that _were_ playing are paused.  Because of client side ticking new sounds could be queued, and those would not be paused.  I have a fix for the next BETA.

**Comment by jurplel** [comment]
Okay, thanks

**Comment by OreCruncher** [comment]
Posted BETA with a fix: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
