### ISSUE TITLE
[Enhancement] Mod specific support for Footsteps...

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/BetterRain#79]
This is to track _new_ requests for specific mod support for the Footstep sounds.  For mods that are currently supported, and there is a problem with a block sound a new entry needs to be created to track that particular issue.  Make sure that the bug information includes the name of the modded block as well as a "should sound like this block in this mod".

Keep in mind that the Footstep logic has fallback sounds based on material type.  A request for a mod should be made only if the fallback sounds don't cut it.
- [x] Forestry (*.0.4.8BETA)
- [x] Biomes O'Plenty (*.0.4.8BETA)
- [x] Growthcraft Community Edition (*.0.4.8BETA)
- [x] ExtrabiomesXL (*.0.4.8BETA)
- [x] Thaumcraft (*.0.4.8BETA)
- [x] Witchery (*.0.4.8BETA)
- [x] Twilight Forest (*.0.5.1BETA)
- [x] Erebus (*.0.5.1BETA)
- [x] Tinkers Construct (*.0.5.3BETA)
- [ ] Natura
- [ ] Enhanced Biomes
- [ ] Highlands
- [ ] Highlands Uncharted Territories
- [ ] Chisel
- [ ] Et Futurum
- [ ] Fossils and Archaeology
- [ ] Ars Magica 2
- [ ] Plant Megapack
- [ ] Harvestcraft
- [ ] The Vegan Option
- [ ] Woodstuff

**Comment by Sunconure11** [comment]
Thaumcraft, Ars Magica 2, Enhanced Biomes, Highlands, Chisel, Various ore mods, and Witchery should be some things you should tackle too.

**Comment by OreCruncher** [comment]
Are there blocks in those mods that require special support?  The ones that have wood/leaves most likely, but the others may not need anything special.

**Comment by Sunconure11** [comment]
Possibly various stones, jewels, and also thaumcraft has all that taint stuff. I suggest looking through them to determine what is most fitting.

Et Futurum (grass paths should really have a different sound) could also benefit, as well as Fossils and Archaeology (has wood and leaves)

**Comment by EthanJJC** [comment]
hi
I use Dynamic Surroundings and Ambience (Music Mod)
But I don't know how add your mod event in Ambience 
When in desert-Sandstorm played music is rain‘s

**Comment by Sunconure11** [comment]
Also, this is for vanilla, but, can you make raw clay blocks not sound like stone when stepped on?

Plant Mega Pack might be worth looking at too, for stepping on its various plants.

Harvestcraft and Growthcraft grains should make similar sounds to wheat when stepped on if they are ripe.

**Comment by OreCruncher** [comment]
Raw clay actually has a sound profile of "sandstone", though it sounds quite similar to the "stone" sound profile.  I guess it would depend on whether clay would have a "wet" sound.  There is a sound profile called "mud" which sounds a little squishy - you can spawn in sponge blocks to get a sense of what it would sound like.

**Comment by OreCruncher** [comment]
The clay block has the dirt sound when walked on in Vanilla.  I may change it to dirt.  I think originally Presence Footsteps had it configured as "concrete" because it looked like concrete and players probably used it as such.  But with the different hard clays and things changing it to dirt shouldn't be a problem.  (I think "mud" may be a bit too much squishy.)

**Comment by Sunconure11** [comment]
The Vegan Option has a jute crop in the latest builds that should play the same sounds that large ferns play when stepped on, IMO.

**Comment by Sunconure11** [comment]
Is it possible to detect blocks and assign sounds via oredictionary definitions? That might be an interesting way to knock out many mod requests, and deal with their sounds, as you cannot support every mod ever, you might want to add ways to hook into existing mods and add support there.

**Comment by OreCruncher** [comment]
In general, yes.  Thanks for reminding me.  I did similar things in my other mod Thermal Recycling when processing recipes.  As a default it would go a long ways.

**Comment by Sunconure11** [comment]
I also suggest allowing users to add onto the oredictionary list if you add that option, so unknown oredictionary definitions can be added.

**Comment by OreCruncher** [comment]
There are quite a number of common ones already - such as the various ores, planks, logs, etc.  It would get the vast majority.  I would have to think about mod specific ones.

**Comment by Sunconure11** [comment]
What I just pushed out as a pull request might add some minor support for AM2, Vegan Option, and a few other mods, including wood stuff. You might want to add a setting for gemstone and obsidian-type blocks though, as I had to put a few under sandstone at the moment.

Picking up mud sounds would help too.

**Comment by Sunconure11** [comment]
Don't accept it yet, I am adding some more stuff to it.

**Comment by Sunconure11** [comment]
Hopefully this works.

**Comment by Sunconure11** [comment]
Okay I think this is safe to merge.

**Comment by OreCruncher** [comment]
Which ones are obisidian and mud like?  There are sound types that have those covered.

**Comment by Sunconure11** [comment]
I mean you should add them to the dictionary if you haven't already

**Comment by Sunconure11** [comment]
Oh, it seems you have added mud and obsidian-like.

**Comment by Sunconure11** [comment]
Also, do blocks such as diamond blocks use a unique sound when stepped on? I'd like to try to conquer some jewel blocks as well.

**Comment by Sunconure11** [comment]
I'm assigning some blocks to proper ore dictionary settings at the moment.

**Comment by OreCruncher** [comment]
The Minecraft defaults for blocks can be found [here](https://github.com/OreCruncher/BetterRain/blob/master/src/main/resources/assets/dsurround/data/footsteps/blockmap.json).  The sound type for diamond and emerald blocks is "composite".  I would have to set up another entry for that.

**Comment by Sunconure11** [comment]
Alright. Expect another pull request with a few AM2 ore dictionary settings shoved into the right entry, and some modded stones added on.

**Comment by Sunconure11** [comment]
Also, it appears if I assign an ore to have the proper ore dictionary settings via minetweaker, it does not pick up on the new sounds. Is there anything you can do about that?

**Comment by OreCruncher** [comment]
Issue with Minetweaker is when it loads.  Scripts are executed when a player connects to the world, which is way past the point of when the Footstep mod initializes.

**Comment by Sunconure11** [comment]
I see. Is there a way to get around the minetweaker issue? I created some custom ores such as copper using this mod (http://www.curse.com/mc-mods/minecraft/224312-customitems) because I didn't want copper with a billion other things, and registered them via the oredictionary.

Maybe it could also hook into stuff via in game names, as well? Such as say, copper ore that is not under any ore dictionary definition.

**Comment by Sunconure11** [comment]
And what about stone bricks and quartz?

**Comment by OreCruncher** [comment]
Minetweaker  - I did something similar with one of my other mods - delaying final init until the last possible moment.  I may be able to do something similar for this.

There weren't any ore dictionary entries for stone bricks or quartz.  Internally they have sound maps of "brickstone" and "marble" respectively.

**Comment by Sunconure11** [comment]
Maybe add entries for them via the oredictionary then, I want to add better support for every mod I can find.

**Comment by OreCruncher** [comment]
I could add those entries in the Forge mappings, but it would have to depend on what the commonly accepted dictionary names would be for stone bricks.  blockQuartz would map to "marble" so I can add that.

**Comment by Sunconure11** [comment]
I'll add marble to the proper definition later today or tomorrow. I'll also look for more common dictionary definitions found in various modpacks and mods, as I have done a bit of that to find various definitions.

**Comment by Sunconure11** [comment]
Also, can I suggest support for the mod woodstuff? I was able to get most of the rudimentary compatibility for it done via the oredictionary, but, I think the bookshelves need to be handled by you.

**Comment by OreCruncher** [comment]
Sounds like it would need a specific config unless there is a requirement for having bookshelves being in the ore dictionary.

**Comment by Sunconure11** [comment]
Their bookshelves have oredictionary support, but, I meant for stuff like the rustling paper and such.

**Comment by Sunconure11** [comment]
Growthcraft 2.5.0 (the preview builds) might need support in the future. I added the cheese entry via the oredictionary for its blocks, and they still sound like stone with this mod installed.

**Comment by OreCruncher** [comment]
I merged the update after I posted the current BETA on CurseForge.

**Comment by Sunconure11** [comment]
Ah, thought something screwed up.

**Comment by OreCruncher** [comment]
Closing enhancements - 1.7.10 version is in maintenance.
