### ISSUE TITLE
Clarification: Altitude Haze

### ISSUE THREAD

**Issue by PitchBright** [OreCruncher/BetterRain#8]
Is this feature based on an IRL thing? I was under the impression that the air becomes clearer (and that visibility improves) as we go up in elevation, IRL.

**Comment by OreCruncher** [comment]
It is more from the perspective of climbing up into the cloud layer.  It's why when it rains the mod makes it hazier at lower altitudes.

**Comment by PitchBright** [comment]
Okay, great. Thanks for the clarification!

**Comment by PitchBright** [comment]
Just a side note: I noticed that the haze is in effect, even when it's not raining. But the haze setting is in the Rain section of the config, which might lead some (myself included) to believe that it's something that's in effect, only when it's raining.

**Comment by OreCruncher** [comment]
Hmmm. Good point.  I will see about cleaning that up.
