### ISSUE TITLE
about surpport other mods

### ISSUE THREAD

**Issue by EthanO3O** [OreCruncher/BetterRain#80]
Hi
I use Dynamic Surroundings and Ambience (Music Mod)
But I don't know how add your mod event in Ambience 
When in desert-Sandstorm played music is rain music

**Comment by OreCruncher** [comment]
I have not used Ambience so I don't know for sure, but based on my reading you would have to filter based on rain as well as being in a desert biome to play (or not play) the rain sound.

**Comment by EthanO3O** [comment]
ooou
so i can not add Sandstorm music in game :(

**Comment by OreCruncher** [comment]
The way Dynamic Surroundings determines if it is a sandstorm rather than rain is:
- It is raining
- The player biome has "desert" in the name

If you can set up a similar rule in Ambience it should match.

**Comment by EthanO3O** [comment]
I will try 
THX

**Comment by OreCruncher** [comment]
Looked at the Ambience config and it doesn't appear to be a way to keep these two in sync.  Nothing I can do about it right now.
