### ISSUE TITLE
[Request] Configurable Biome Fog Fade-in/out duration

### ISSUE THREAD

**Issue by Ariannae** [OreCruncher/BetterRain#82]
Similar to the issue I had with Desert storms a while back, where they would transition extremely quickly, where it made for a somewhat jarring transition. I'd love to see a configuration added to change up how long the biome fog takes to settle in. Ie, instead of going from a Swamp -> River -> Swamp and having the fog quickly change upon each transition, I'd like to see the fog take a longer time to dissipate, as well as a longer time to come back to full strength. Hopefully that makes sense.

**Comment by OreCruncher** [comment]
It does.  I have noticed the same thing.  I haven't thought up a good way to handle.  It's like there needs to be a delay going up or down in fog intensity in the case of crossing several biomes quickly.

EDIT: I could change the fog delta factor to be less, which would require more time to fade in/out.  But then when a player leaves a foggy situation they may want to clear quickly.

EDIT2: Also, not sure if you noticed but the fog color transition time works out to be different from the fog density transition time.  I need to work out the math to make it that any color transition is scaled to the fog density transition so it blends better.

**Comment by Ariannae** [comment]
Now, I'm not entirely sure here, and it could also be due to other mods I'm using (Realistic Terrain Generation), but BoP's Ominous Woods biome seemed to have its biome fog get stronger the further into the biome you were. So if you were on the outskirts of the biome, the fog would barely be noticeable. Walk a few blocks into the biome, and the fog really started to pick up. Perhaps using that sort of method would work better than using a timer-based system? Kind of like how you have Elevation haze set up, but on an X/Z axis instead, dependent on biome, maybe?

**Comment by OreCruncher** [comment]
I looked at how BoP does the fog and it does take an interesting approach.  Problem is that it can be intensive - it surveys the area around the player and makes several calculations as to what it wants to do for fog.  I am still studying how they did it to get ideas on how I can improve the fog I have.

The other challenge with mods that try to control fog is that they are doing it independent of each other and could wind up in a fog tug of war.  I have to ask the BoP guys if they are willing to make further changes to the 1.7.10 code base for fog so we can get a better experience.

**Comment by Ariannae** [comment]
Actually, and this is a tad bit off topic for this request, but would it be possible to have the sounds based off of a similar system, assuming you find a way to implement it in a less intensive manner? This would alleviate the other issue I had where biome transitions could result in abrupt changes in sound. If you manage to implement a system similar to BoP's fog setup, and have the sound's volume use the similar/same system, it should also result in extremely smooth transitions. Ie, on the outskirts of a Jungle, you would hear the wildlife sounds at a low volume/barely audible, and as you get further inside the sound gets louder up to its current volume. It might help with Issue #86 as well.

**Comment by OreCruncher** [comment]
It would be possible to do it with sounds.  Simplistically the way it would work:
- Survey an area around the player to collect the biomes in the region as well as their weight (i.e. the plains biome was counted 10 times, river 5, desert 13, etc.)
- All the biome sounds from all those areas would be played.  The volume, however, of the sounds would be scaled based on a biomes representation in the region.  For example, if the region was 10x10 in size and there were 20 plains biomes the sounds from plains would be 20% of what it would be normally (20 / 10x10).

I would have to think on this.  It would be more expensive computationally not to mention would increase the load on the sound system.  For players with more current sound cards it shouldn't be too much a problem, but for those playing on a "potato" it would be a challenge.

EDIT: I am going to break the sound one out into a separate item.  I want to do some tinkering on it.

**Comment by OreCruncher** [comment]
I have the fog working in a similar fashion to the sound mentioned above.  Details:
- The biomes are weighted as for sounds.  Implementation wise I reuse the data collected for sounds during that tick.  Helps mitigate processing overhead.
- Fog colors/densities are collected from represented biomes and then scaled based on the amount of representation.

The net effect is that fog transition actually starts outside of the applicable biomes, and don't reach full intensity until the players is fully within.  This causes a blending of fog effects at biome borders.  The algorithm also takes into account fog due to desert sandstorms.

**Comment by OreCruncher** [comment]
Posted *.0.5.0BETA to CurseForge with this fog transition change.  Let me know what you think.

**Comment by Ariannae** [comment]
Way, way better transitions than before, awesome work. It flows far better from biome to biome.
