### ISSUE TITLE
[ENHANCEMENT] Configurable classifications for mod added biomes

### ISSUE THREAD

**Issue by Syndaryl** [OreCruncher/BetterRain#86]
A file that maps your supported biome types to new biomes introduced by mods (such as BOP) - Chaparelle being considered equivalent to plains, for example. Right now I walk out of a birch forest (with lovely background environment sound) into Chaparelle and it's dramatically absent. Walk into a river sub-biome in Chaparelle and it's back.

**Comment by OreCruncher** [comment]
Hmm....if I did add something along these lines it would operate like this:
- Match against the biome name as defined in the biome record in Forge/Minecraft.
- If no match, see if there is a user configured alias for that biome name.  If so, match against that alias.
- If still no match, then do nothing.

In this case you would make a configuration entry like "Chaparelle=Plains" (or any other modded biome).

EDIT: Of course I am interested in any missing biome info.  I can add Chaparelle to the internal matching regex so any mod that adds Chaparelle would have the configuration out of the box.

**Comment by Syndaryl** [comment]
I'll keep an ear/eye out for others.

**Comment by ghost** [comment]
This... I like this very much.  Hope to see it happen.

**Comment by OreCruncher** [comment]
It will be going in at the start of the next release cycle.

**Comment by OreCruncher** [comment]
Posted *.0.5.0BETA to CurseForge with this change.
